// src/constants/womenFashionBrands.js
export const globalBrands = [
  "1More",
  "2Eros",
  "2XU",
  "361°",
  "3INA",
  "3M",
  "4F",
  "7 For All Mankind",
  "8BitDo",
  "A Bathing Ape",
  "A.P.C.",
  "Aaiko",
  "Aaptiv",
  "Abercrombie & Fitch",
  "Absolut",
  "Acana",
  "Acer",
  "Acne Studios",
  "Acqua di Parma",
  "Acronym",
  "Adanola",
  "Adidas",
  "Adobe",
  "AEG",
  "Aerin",
  "Aesop",
  "Afends",
  "Agent Provocateur",
  "Agolde",
  "Aigle",
  "Aime Leon Dore",
  "Airbnb",
  "Akai",
  "Akasa",
  "Akris",
  "Aldo",
  "Alessi",
  "Alexander McQueen",
  "Alexander Wang",
  "Alex and Ani",
  "Alienware",
  "All Saints",
  "Allbirds",
  "Aloysius",
  "Alpha Industries",
  "Alpina",
  "Altuzarra",
  "Amazon Basics",
  "Amazon Essentials",
  "Ambre Sultan",
  "AMD",
  "American Apparel",
  "American Eagle",
  "Amiri",
  "Amouage",
  "Anastasia Beverly Hills",
  "Anchor",
  "Ancient Greek Sandals",
  "Anello",
  "Anine Bing",
  "Anker",
  "Anne Klein",
  "Anthropologie",
  "Antler",
  "Anyma",
  "Apc",
  "Apivita",
  "Apple",
  "Aquascutum",
  "Arcelik",
  "Arket",
  "Armani",
  "Armani Exchange",
  "Arper",
  "Arte",
  "Arteza",
  "Artisan",
  "Asahi",
  "Asics",
  "ASOS",
  "Astral",
  "Astro",
  "Asus",
  "AT&T",
  "Atelier Cologne",
  "Athleta",
  "Atmos",
  "Atomic",
  "Audio-Technica",
  "Audiolux",
  "Aukey",
  "Aurelia",
  "Authenticity",
  "Aveeno",
  "Avene",
  "Avon",
  "Awake NY",
  "Axe",
  "Ayurveda",
  "Azzaro",
  "B&O",
  "Babyliss",
  "Babyzen",
  "Bacardi",
  "Badgley Mischka",
  "Bagatelle",
  "Baggu",
  "Bague",
  "Balenciaga",
  "Ball",
  "Bally",
  "Balmain",
  "Banana Republic",
  "Bang & Olufsen",
  "Bao Bao Issey Miyake",
  "Bape",
  "Barbour",
  "Bario Neal",
  "Barker",
  "Barnes & Noble",
  "Baseus",
  "Bathing Ape",
  "BaubleBar",
  "Baxter of California",
  "BCBG Max Azria",
  "Beach Riot",
  "Bearpaw",
  "Beats",
  "Beautiful People",
  "Becca",
  "Beckham",
  "Bed Bath & Beyond",
  "Bedgear",
  "Beko",
  "Belkin",
  "Bellroy",
  "Ben Sherman",
  "Benefit",
  "Bentley",
  "Bergdorf Goodman",
  "Bershka",
  "Best Buy",
  "Betts",
  "Beyerdynamic",
  "BH Cosmetics",
  "Billabong",
  "Billion Dollar Brows",
  "Birkenstock",
  "Bisou",
  "Bite Beauty",
  "Blackberry",
  "Blackstone",
  "Blanc",
  "Blazer",
  "Bleu de Chanel",
  "Blind",
  "Bloch",
  "Blondo",
  "Bloomingdale's",
  "Blue Nile",
  "Bluetti",
  "Bobbi Brown",
  "Boden",
  "Body Shop",
  "Bodum",
  "Bombas",
  "Bonobos",
  "Boohoo",
  "Bora Bora",
  "Bose",
  "Boss",
  "Bottega Veneta",
  "Bowers & Wilkins",
  "Box",
  "Braun",
  "Breitling",
  "Brioni",
  "British Airways",
  "Brooks Brothers",
  "Brooks Running",
  "Brother",
  "Brown Thomas",
  "Brunello Cucinelli",
  "BSA",
  "BTS",
  "Bucherer",
  "Budweiser",
  "Buffalo",
  "Bulgari",
  "Bumble and Bumble",
  "Burberry",
  "Burton",
  "Butterfly Twists",
  "Byredo",
  "C&A",
  "Cacique",
  "Cafune",
  "Calvin Klein",
  "Camper",
  "Canada Goose",
  "Canon",
  "Cantu",
  "Capella",
  "Carhartt",
  "Carolina Herrera",
  "Cartier",
  "Casio",
  "Catbird",
  "Caterpillar",
  "Catherine Malandrino",
  "Caudalie",
  "CeraVe",
  "Celine",
  "Centaur",
  "Chaco",
  "Champion",
  "Chanel",
  "Chaos",
  "Charles & Keith",
  "Charles Tyrwhitt",
  "Charlotte Russe",
  "Charlotte Tilbury",
  "Charms",
  "Charter Club",
  "Cheap Monday",
  "Cheerios",
  "Chesterfield",
  "Chevron",
  "Chi",
  "Chicco",
  "Chie Mihara",
  "Chinese Laundry",
  "Chloe",
  "Chopard",
  "Christian Dior",
  "Christian Louboutin",
  "Chrome Hearts",
  "Citizens of Humanity",
  "Citizen",
  "Clarins",
  "Clarks",
  "Clinique",
  "Closet London",
  "Club Monaco",
  "Coach",
  "Coca Cola",
  "Coccinelle",
  "Cole Haan",
  "Colette",
  "Collina Strada",
  "Columbia",
  "Comme des Garcons",
  "Common Projects",
  "Comptoir des Cotonniers",
  "Conair",
  "Converse",
  "Cool",
  "Cooler Master",
  "Corsair",
  "Corteiz",
  "COS",
  "Costco",
  "Cotopaxi",
  "Cotton On",
  "Covergirl",
  "CP Company",
  "Crate & Barrel",
  "Creative",
  "Creed",
  "Crest",
  "Crocs",
  "Crossbody",
  "Cucinelli",
  "Cuisinart",
  "Cult Gaia",
  "Cuyana",
  "CyberPowerPC",
  "Dagne Dover",
  "Dainese",
  "Daisuke Obana",
  "Daniel Wellington",
  "Danner",
  "Dansko",
  "Darling",
  "David Jones",
  "David Yurman",
  "De Beers",
  "DeBrand",
  "Deciem",
  "Defacto",
  "Dell",
  "Delsey",
  "Delta",
  "Denon",
  "Department",
  "Dermalogica",
  "Desigual",
  "DeWalt",
  "DHL",
  "Diane von Furstenberg",
  "Dickies",
  "Diesel",
  "Dior",
  "Disney",
  "DKNY",
  "Dockers",
  "Dolce & Gabbana",
  "Dole",
  "Domyos",
  "Dooney & Bourke",
  "Doritos",
  "Dove",
  "Dr. Martens",
  "Dr. Scholl's",
  "Dragon",
  "Dries Van Noten",
  "Dropbox",
  "Drunk Elephant",
  "Dsquared2",
  "Ducati",
  "Dune London",
  "Dunhill",
  "DuPont",
  "Durex",
  "Dyson",
  "E.L.F.",
  "Eagle",
  "Earnest Sewn",
  "Eastpak",
  "eBags",
  "Ebay",
  "Ecco",
  "Edifier",
  "Egoist",
  "Eight & Bob",
  "Eileen Fisher",
  "Element",
  "Elizabeth Arden",
  "Ellesse",
  "Elsa Peretti",
  "Emilio Pucci",
  "Emporio Armani",
  "Endura",
  "Energizer",
  "Envy",
  "Epic Games",
  "Epson",
  "Equipment",
  "Ermenegildo Zegna",
  "Escada",
  "Essie",
  "Estee Lauder",
  "EssilorLuxottica",
  "Etam",
  "Eternity",
  "Etude House",
  "Eucerin",
  "Everlane",
  "Every Man Jack",
  "Evian",
  "Express",
  "Eyeko",
  "Fabletics",
  "Facebook",
  "Facetasm",
  "Falke",
  "Fame",
  "Farfetch",
  "Fashion Nova",
  "Fay",
  "Fear of God",
  "FedEx",
  "Felix",
  "Fendi",
  "Fenty Beauty",
  "Ferrari",
  "Ferragamo",
  "Fidelity",
  "Figs",
  "Fila",
  "Filippa K",
  "Finch",
  "Fiorelli",
  "Fisher-Price",
  "Fitbit",
  "Fjällräven",
  "Flash",
  "Florsheim",
  "Focal",
  "Fom",
  "Forever 21",
  "Fortnite",
  "Fossil",
  "Fracap",
  "Frame",
  "Frank And Oak",
  "Fred Perry",
  "Free People",
  "French Connection",
  "Fresh",
  "Friday",
  "Frye",
  "Fuji",
  "Furla",
  "G-Star RAW",
  "Gabbana",
  "Gabriela Hearst",
  "Gal Gadot",
  "Galeries Lafayette",
  "Game",
  "Ganni",
  "Gap",
  "Garmin",
  "Gatorade",
  "Geberit",
  "Gentle Monster",
  "George",
  "Giambattista Valli",
  "Gianni Versace",
  "Gift",
  "Gildan",
  "Giorgio Armani",
  "Givenchy",
  "Glamglow",
  "Globe",
  "Glory",
  "Glossier",
  "GMT",
  "GNC",
  "Goat",
  "Godiva",
  "Golden Goose",
  "Goldwell",
  "Google",
  "Gorjana",
  "Grado",
  "Graff",
  "Graham",
  "Grenson",
  "Greyhound",
  "Grlfrnd",
  "Grohe",
  "Grounding",
  "Groupe",
  "Gucci",
  "Guess",
  "Guinness",
  "Gulf",
  "Gymshark",
  "H&M",
  "Haagen-Dazs",
  "Habitat",
  "Haider Ackermann",
  "Hamilton",
  "Hammitt",
  "Hanky Panky",
  "Happy",
  "Hard Rock",
  "Harley Davidson",
  "Harman Kardon",
  "Harry Winston",
  "Havaianas",
  "Hayden",
  "Head",
  "Health",
  "Hedley & Bennett",
  "Heineken",
  "Helly Hansen",
  "Hennessy",
  "Hermes",
  "Heron Preston",
  "Herschel Supply Co.",
  "Hewlett Packard",
  "HiFiMan",
  "Hilary",
  "Hilton",
  "Himmeli",
  "Hipster",
  "History",
  "HM",
  "Hoka One One",
  "Holiday",
  "Hollister",
  "Home Depot",
  "Honda",
  "Hook",
  "Hot Topic",
  "HP",
  "HTC",
  "Hudson Jeans",
  "Hugo Boss",
  "Human Made",
  "Hunter",
  "Hurley",
  "HyperX",
  "IBM",
  "Ice",
  "Iconery",
  "IKEA",
  "Iittala",
  "Illuminati",
  "Iman",
  "Imperial",
  "In The Style",
  "Inditex",
  "Infinity",
  "Ingersoll",
  "Innisfree",
  "Intel",
  "Intex",
  "Invicta",
  "Isaia",
  "Isabel Marant",
  "Issey Miyake",
  "IWC Schaffhausen",
  "J.Crew",
  "J.W.Anderson",
  "Jabra",
  "Jack & Jones",
  "Jack Daniels",
  "Jack Wolfskin",
  "Jacquemus",
  "Jaeger-LeCoultre",
  "James Allen",
  "JanSport",
  "Jaybird",
  "JBL",
  "Jennifer Fisher",
  "Jil Sander",
  "Jimmy Choo",
  "Jnco",
  "John Lewis",
  "John Varvatos",
  "Johnny Was",
  "Johnson & Johnson",
  "Joma",
  "Jordan",
  "Joseph",
  "Joules",
  "Judith Leiber",
  "Jujube",
  "Jura",
  "Just Cavalli",
  "JVC",
  "Kappa",
  "Kate Spade",
  "Keds",
  "Kelty",
  "Kendra Scott",
  "Kenzo",
  "Kering",
  "Keurig",
  "Kiehl's",
  "Kiko Milano",
  "Kindle",
  "King",
  "Kipling",
  "Kit",
  "KitchenAid",
  "Klipsch",
  "Kmart",
  "Knomo",
  "Kohl's",
  "Kooples",
  "Koss",
  "Kylie Cosmetics",
  "L'Oreal",
  "L.L.Bean",
  "La Mer",
  "La Perla",
  "La Prairie",
  "La Roche-Posay",
  "Lacoste",
  "Laduree",
  "Lamborghini",
  "Lancome",
  "Land Rover",
  "Lands' End",
  "Lane Bryant",
  "Lanvin",
  "Lark",
  "Laura Mercier",
  "Lavanila",
  "Le Creuset",
  "Le Labo",
  "Le Specs",
  "League",
  "Lemaire",
  "Lenovo",
  "Les Copains",
  "Levi's",
  "LG",
  "Liberty",
  "Life",
  "Limited",
  "Lindt",
  "Linen",
  "Links",
  "Linus",
  "Liz Claiborne",
  "Loewe",
  "Logitech",
  "Longchamp",
  "Longines",
  "Look",
  "Loro Piana",
  "LOT",
  "Louis Vuitton",
  "Love",
  "Lowe's",
  "LTB",
  "Lucky Brand",
  "Lud",
  "Lululemon",
  "Luna",
  "Luxury",
  "Luxe",
  "Lynx",
  "M.A.C",
  "MAC",
  "Mace",
  "Mack Weldon",
  "Macy's",
  "Madden Girl",
  "Madewell",
  "Madison",
  "Magic",
  "Maison Margiela",
  "Makeupforever",
  "Mamma Mia",
  "Man",
  "Mango",
  "Marc Ecko",
  "Marc Jacobs",
  "Marciano",
  "Marine",
  "Marks & Spencer",
  "Marlboro",
  "Marshall",
  "Marvis",
  "Massimo Dutti",
  "Master & Dynamic",
  "Matalan",
  "Matrix",
  "Maui Jim",
  "Mauri",
  "Max Factor",
  "Max Mara",
  "Maybelline",
  "McDonald's",
  "Me&Ro",
  "Medusa",
  "Melissa",
  "Mercedes",
  "Merrell",
  "Meze Audio",
  "Michael Kors",
  "Microsoft",
  "Mido",
  "Mikimoto",
  "Millennium",
  "Miller",
  "Minnetonka",
  "Missoni",
  "Miu Miu",
  "MM6",
  "Moncler",
  "Monday",
  "Money",
  "Monki",
  "Monoprice",
  "Monster",
  "Montblanc",
  "Moomin",
  "Moose Knuckles",
  "Mori Lee",
  "Moschino",
  "Motorola",
  "Mountain Hardwear",
  "Moynat",
  "MSI",
  "MTV",
  "Muji",
  "Mulberry",
  "Murad",
  "Museum",
  "Mustang",
  "Naf Naf",
  "Napapijri",
  "NASA",
  "Natura",
  "Nautica",
  "NBA",
  "Neiman Marcus",
  "Nespresso",
  "Nestle",
  "Netflix",
  "New Balance",
  "New Look",
  "Next",
  "NFL",
  "Nike",
  "Nikon",
  "Nine West",
  "Nintendo",
  "Nixon",
  "No7",
  "Nobody Denim",
  "Nokia",
  "Nordstrom",
  "North Face",
  "Northface",
  "Nothing",
  "Notre Dame",
  "Novak",
  "NSF",
  "Nvidia",
  "NYX Professional Makeup",
  "O'Neill",
  "Oakley",
  "Ocean",
  "Off-White",
  "Oil of Olay",
  "Old Navy",
  "Old Spice",
  "Olive",
  "Oliver Peoples",
  "Omega",
  "One Plus",
  "Oneida",
  "Onitsuka Tiger",
  "Onyx Boox",
  "Oofos",
  "OppoSuits",
  "Oral-B",
  "Orange",
  "Organic",
  "Origins",
  "Oris",
  "Orlebar Brown",
  "Orvis",
  "Oscar de la Renta",
  "Osprey",
  "Other Stories",
  "Oui",
  "Outdoor Research",
  "Outward Hound",
  "Ovation",
  "Overlap",
  "Oxford",
  "P&G",
  "Pacsun",
  "Palladium",
  "Palm Angels",
  "Pandora",
  "Panerai",
  "Pantene",
  "Paper",
  "Parfois",
  "Parker",
  "Patagonia",
  "Patek Philippe",
  "Patrizia Pepe",
  "Paul & Joe",
  "Paul Smith",
  "Pavement",
  "Peak Design",
  "Pearl",
  "Pendleton",
  "Pepsi",
  "Perfect",
  "Perfekt",
  "Perry Ellis",
  "Peter Millar",
  "Peugeot",
  "PGA",
  "Philips",
  "Philosophy",
  "Phoenix",
  "Phoebe Philo",
  "Phuket",
  "Piaget",
  "Pierre Cardin",
  "Pierre Hardy",
  "Pilot",
  "Pioneer",
  "Plantronics",
  "Playboy",
  "PlayStation",
  "Plaza",
  "Pleats Please",
  "Plinius",
  "Polo Ralph Lauren",
  "Polti",
  "Pop",
  "Porcupine",
  "Porsche Design",
  "Portuguese",
  "Pottery Barn",
  "Prada",
  "Precious",
  "Pretty Little Thing",
  "Prime",
  "Primark",
  "Prince",
  "Private",
  "Proenza Schouler",
  "Prom",
  "Propet",
  "Propper",
  "Puma",
  "Purell",
  "Purple",
  "Qantas",
  "Quay",
  "Queen",
  "Quiksilver",
  "R.M.Williams",
  "Rachel Zoe",
  "Rag & Bone",
  "Ralph Lauren",
  "Rare Beauty",
  "Razer",
  "Ray-Ban",
  "Rebecca Minkoff",
  "Red Bull",
  "Red Wing",
  "Reebok",
  "Reed Krakoff",
  "Reformation",
  "Reiss",
  "Repetto",
  "Reserve",
  "Ressence",
  "Revlon",
  "Rich",
  "Rick Owens",
  "Rider",
  "Rimmel",
  "Rimowa",
  "River Island",
  "Rixo",
  "Roberto Cavalli",
  "Rodd & Gunn",
  "Rolex",
  "Roma",
  "Rothy's",
  "Royal",
  "RRL",
  "Rupert Sanderson",
  "Russian",
  "Sabo",
  "Sacai",
  "Saks Fifth Avenue",
  "Salomon",
  "Salvatore Ferragamo",
  "Sam Edelman",
  "Samsung",
  "Samsonite",
  "Samsoe Samsoe",
  "Sanctuary",
  "Sanderson",
  "Sandqvist",
  "Sanuk",
  "Saucony",
  "Savage X Fenty",
  "Scala",
  "Scandinavian",
  "Scarlett",
  "Schott",
  "Scosha",
  "Scotch & Soda",
  "Scott",
  "Sea",
  "Seiko",
  "Sennheiser",
  "Sephora",
  "Seven",
  "Sharpie",
  "Shell",
  "Shiseido",
  "Shure",
  "Siemens",
  "Silver",
  "Simons",
  "Sinclair",
  "Skechers",
  "Skims",
  "Skullcandy",
  "Slip",
  "Smart",
  "Smeg",
  "Smith",
  "Smythson",
  "Snapchat",
  "Soho",
  "Solange",
  "Sole Society",
  "Solid",
  "Sonia Rykiel",
  "Sony",
  "Soundcore",
  "Spanx",
  "Spark",
  "Speedo",
  "Sperry",
  "Spider",
  "Spotify",
  "Stance",
  "Starbucks",
  "State",
  "SteelSeries",
  "Stella McCartney",
  "Steve Madden",
  "Stone Island",
  "Stuart Weitzman",
  "Studio",
  "Sturdy",
  "Subway",
  "Sugarhill Brighton",
  "Sun",
  "Sunglass Hut",
  "Superdry",
  "Superga",
  "Supreme",
  "Surf",
  "Swatch",
  "Swedish Hasbeens",
  "Swimming",
  "Swiss",
  "T3",
  "Tab",
  "Tadashi Shoji",
  "Tag Heuer",
  "Take",
  "Talbot",
  "TaoTronics",
  "Target",
  "Ted Baker",
  "Temple",
  "Tennis",
  "Tesco",
  "Tesla",
  "Teva",
  "The Kooples",
  "The Limited",
  "The North Face",
  "The Ordinary",
  "The Row",
  "Theia",
  "Theory",
  "Thom Browne",
  "Thomas Sabo",
  "Three",
  "Tidal",
  "Tiffany & Co.",
  "Timberland",
  "Tissot",
  "TJ Maxx",
  "Tod's",
  "Tom Ford",
  "Tom Tailor",
  "Tommy Hilfiger",
  "Tony Burch",
  "Topo Designs",
  "Tory Burch",
  "Total",
  "Totto",
  "Town",
  "Toyota",
  "Transport",
  "Travel",
  "Tricker's",
  "True Religion",
  "Tumi",
  "Turkish",
  "Twitter",
  "Two",
  "Uber",
  "Ugg",
  "Ulta",
  "Under Armour",
  "Undercover",
  "Uniqlo",
  "Unity",
  "Universal",
  "UPS",
  "Urban Decay",
  "Urban Outfitters",
  "US Polo Assn",
  "Utopia",
  "V&A",
  "Vacheron Constantin",
  "Vagabond",
  "Valentino",
  "Valerie",
  "Van Cleef & Arpels",
  "Vans",
  "Vaseline",
  "Vaughan",
  "Vegan",
  "Velvet",
  "Vera Bradley",
  "Versace",
  "Very",
  "Vespa",
  "Vetements",
  "Via Spiga",
  "Vibe",
  "Victoria Beckham",
  "Victoria's Secret",
  "Victorinox",
  "Vilebrequin",
  "Vineyard Vines",
  "Vintage",
  "Virgin",
  "Visa",
  "Vision",
  "Vita",
  "Vivienne Westwood",
  "Vodka",
  "Vogue",
  "Volkswagen",
  "Volvo",
  "Warby Parker",
  "Water",
  "Wave",
  "Weekday",
  "Wellies",
  "West Elm",
  "Westside",
  "Whirlpool",
  "Whistles",
  "White",
  "Whole Foods",
  "Wild",
  "Williams Sonoma",
  "Wilson",
  "Wind",
  "Wine",
  "Wired",
  "Wolford",
  "Wonder",
  "Wood",
  "Woolrich",
  "World",
  "X-Box",
  "Xiaomi",
  "Yamaha",
  "Yeezy",
  "Yes",
  "YSL",
  "Yves Saint Laurent",
  "Zadig & Voltaire",
  "Zales",
  "Zara",
  "Zenith",
  "Zero",
  "Zimmermann",
  "Zion",
  "Zone",
  "Zoom",
  "Zuhair Murad",
  "Zulu",
  "Zwilling",
  "Zyrtec",
  // Turkish Brands
  "Abbate",
  "Abiye",
  "Actuel",
  "Adil Isik",
  "Aker",
  "Akris Point",
  "Altınyıldız",
  "Armine",
  "Atasay",
  "Avva",
  "Ayakkabı Dünyası",
  "Bambi",
  "Batik",
  "Beymen",
  "Biltem",
  "Boyner",
  "Can Bonomo",
  "Ceket",
  "Cemile",
  "Collezione",
  "Damat",
  "DeFacto",
  "Derimod",
  "Desa",
  "Divan",
  "Eda",
  "Efendi",
  "Eker",
  "Enzo",
  "Erdem",
  "Etek",
  "FLO",
  "Fortensia",
  "Goksu",
  "Haluk",
  "Hatemoğlu",
  "Hazal",
  "İnci",
  "İpekyol",
  "Kahve",
  "Kigili",
  "Koton",
  "LC Waikiki",
  "Lufian",
  "Machka",
  "Mango Turkey",
  "Meridyen",
  "Modanisa",
  "Modavin",
  "Network",
  "Nihan",
  "Nurten",
  "Oxxo",
  "Pierre Cardin Turkey",
  "Pitti",
  "Sarar",
  "Setrms",
  "Silk & Cashmere",
  "Süvari",
  "Tanca",
  "Tekbir",
  "Triko",
  "Tuğba",
  "Twist",
  "U.S. Polo Assn Turkey",
  "Vakko",
  "Vera Moda Turkey",
  "Yargıcı",
  "Yeni",
  "Zellbury",
  // Korean Brands
  "3CE",
  "8Seconds",
  "ADER Error",
  "Ahn Jung-geun",
  "Aland",
  "Ami",
  "Anderssonbell",
  "Aritaum",
  "ATEEZ",
  "Baekhyun",
  "Banila Co",
  "Bean Pole",
  "Beauty of Joseon",
  "Beyond",
  "Blackpink",
  "BTS Official",
  "Canmake Korea",
  "CJ CheilJedang",
  "Clé de Peau Beauté Korea",
  "Cosrx",
  "Dear Dahlia",
  "Dior Korea",
  "Dr. Jart+",
  "Eider",
  "Etude",
  "Exo",
  "Fila Korea",
  "G-Dragon",
  "Galaxy",
  "Gentle Black",
  "Gmarket",
  "Hera",
  "Holika Holika",
  "Hyein",
  "Hyuna",
  "IU",
  "Jennie",
  "Jimin",
  "Jung Kook",
  "Kahi",
  "Kiko",
  "Klairs",
  "Korean Air",
  "Laneige",
  "Lisa",
  "LG Electronics",
  "Mamonde",
  "Missha",
  "Monki Korea",
  "Nature Republic",
  "NCT",
  "Neogen",
  "NewJeans",
  "Nike Korea",
  "Ohuhu",
  "Olive Young",
  "Peripera",
  "Pony Effect",
  "Red Velvet",
  "Rosé",
  "Samsung Electronics",
  "Seventeen",
  "Shinsegae",
  "SK-II Korea",
  "Skinfood",
  "Some By Mi",
  "Suga",
  "Sulwhasoo",
  "The Face Shop",
  "The Saem",
  "TonyMoly",
  "Twice",
  "V",
  "Wonder Girls",
  "Yves",
  // Chinese Brands
  "361 Degrees",
  "Anta",
  "Aokang",
  "ASUS China",
  "Balabala",
  "Bosideng",
  "Brands China",
  "ByteDance",
  "Chando",
  "CHCEDO",
  "Chow Tai Fook",
  "CMGE",
  "DJI",
  "Doucal's China",
  "Erdos",
  "Florasis",
  "Giordano",
  "Gome",
  "Haier",
  "HLA",
  "Honor",
  "Huawei",
  "Jiangnan Buyi",
  "Kappa China",
  "King Long",
  "La Chapelle",
  "Li-Ning",
  "Metersbonwe",
  "Miaozhen",
  "Midea",
  "Mo&Co",
  "Ochirly",
  "OnePlus China",
  "OPPO",
  "Only China",
  "Osim",
  "Peacebird",
  "Perfect Diary",
  "Playboy China",
  "Puma China",
  "Qiaodan",
  "Realme",
  "Red Dragonfly",
  "Septwolves",
  "Skechers China",
  "Suning",
  "Taobao",
  "Tencent",
  "TikTok",
  "Tmall",
  "Xtep",
  "Youngor",
  "Zara China",
  // Japanese Brands
  "A Bathing Ape Japan",
  "Asics Japan",
  "Beams",
  "Burton Japan",
  "Casio Japan",
  "Citizens Japan",
  "Comme des Garcons Japan",
  "Cosme Decorte",
  "DHC",
  "Fancl",
  "Fast Retailing",
  "GU",
  "Hada Labo",
  "Issey Miyake Japan",
  "Junya Watanabe",
  "Kenzo Japan",
  "Muji Japan",
  "Neighborhood",
  "Nintendo Japan",
  "Porter",
  "Sacai Japan",
  "Shiseido Japan",
  "Sony Japan",
  "Takashi Murakami",
  "Undercover Japan",
  "Uniqlo Japan",
  "Visvim",
  "Yohji Yamamoto",
  // Russian Brands
  "12Storeez",
  "Adidas Russia",
  "Baon",
  "Befree",
  "Bosco",
  "Calzedonia Russia",
  "Concept Club",
  "Cropp Russia",
  "Denim",
  "Etam Russia",
  "Gloria Jeans",
  "House Russia",
  "Incity",
  "Kari",
  "Lamoda",
  "Love Republic",
  "Mango Russia",
  "Mohito Russia",
  "O'stin",
  "Oysho Russia",
  "Puma Russia",
  "Reserved Russia",
  "Sela",
  "Sinsay Russia",
  "Springfield Russia",
  "Stradivarius Russia",
  "Tom Tailor Russia",
  "United Colors Russia",
  "Zara Russia",
  // European Brands (Additional)
  "Acne Studios Sweden",
  "Adidas Germany",
  "Aigner",
  "Aigle France",
  "Alberto",
  "Armani Italy",
  "Aspesi",
  "Barbour UK",
  "Birkenstock Germany",
  "Brunello Italy",
  "Burberry UK",
  "COS Sweden",
  "Diesel Italy",
  "Ermenegildo Italy",
  "Fjällräven Sweden",
  "Gant Sweden",
  "Geox Italy",
  "H&M Sweden",
  "Hugo Boss Germany",
  "IKEA Sweden",
  "Intimissimi Italy",
  "Lacoste France",
  "Levi's Europe",
  "Louis Vuitton France",
  "Mango Spain",
  "Massimo Italy",
  "Max Mara Italy",
  "Moncler Italy",
  "Moschino Italy",
  "Pandora Denmark",
  "Prada Italy",
  "Pull & Bear Spain",
  "Reserved Poland",
  "Scotch Netherlands",
  "Stradivarius Spain",
  "Tommy Hilfiger Europe",
  "Versace Italy",
  "Zara Spain",
  // Australian Brands
  "Aesop Australia",
  "Billabong Australia",
  "Country Road",
  "Decjuba",
  "Dotti",
  "Forever New",
  "Gorman",
  "Industrie",
  "Just Jeans",
  "Kathmandu",
  "Kookai",
  "Mimco",
  "Oroton",
  "Portmans",
  "Quiksilver Australia",
  "R.M.Williams Australia",
  "Rip Curl",
  "Sass & Bide",
  "Seafolly",
  "Sheike",
  "Sportsgirl",
  "Surf Dive 'n' Ski",
  "Tigerlily",
  "Witchery",
  // Arabic/Middle Eastern Brands
  "Abdulla Al Otaiba",
  "Al Jalila",
  "Al Tayer",
  "Bloom",
  "Chalhoub",
  "Damas",
  "Faces",
  "Galeries Lafayette Dubai",
  "Gold & Diamond Park",
  "Harvey Nichols Dubai",
  "Jashanmal",
  "Level Shoes",
  "Mahalli",
  "Mall of Emirates",
  "Namshi",
  "Ounass",
  "Paris Gallery",
  "Rivoli",
  "Salam Stores",
  "Shukr",
  "Sun & Sand Sports",
  "The Giving Movement",
  "Virgin Megastore",
  "Wojooh",
  // Indian Brands
  "Ajio",
  "Allen Solly",
  "Biba",
  "Bombay Dyeing",
  "Fabindia",
  "FabAlley",
  "Flying Machine",
  "Forest Essentials",
  "Globus",
  "Indya",
  "Jockey India",
  "Kama Ayurveda",
  "Lakme",
  "Levi's India",
  "Lifestyle",
  "Manyavar",
  "Max Fashion",
  "Melange",
  "Myntra",
  "Nykaa",
  "Only India",
  "Pantaloons",
  "Peter England",
  "Reliance Trends",
  "Shree",
  "United Colors India",
  "Van Heusen India",
  "Vero Moda India",
  "W",
  // African Brands
  "African Prints",
  "Afrikrea",
  "Akosombo",
  "Ankara",
  "Asake",
  "Deola Sagoe",
  "Edun",
  "Ethical Fashion",
  "Johannesburg",
  "Kente",
  "Lagos Fashion",
  "MaXhosa",
  "Nigeria Fashion",
  "Ozwald Boateng",
  "Rich Mnisi",
  "South African Fashion",
  "Thebe Magugu",
  "Ubuntu",
  "Woolworths South Africa",
  // Latin American Brands
  "Arezzo",
  "Animale",
  "Carmen Steffens",
  "C&A Brazil",
  "Colcci",
  "Farm",
  "Havaianas Brazil",
  "Melissa Brazil",
  "Osklen",
  "Renner",
  "Riachuelo",
  "Scala Brazil",
  "Via Marte",
  "Zara Brazil",
  // Tech & Electronics Brands
  "Alienware",
  "AMD",
  "Anker",
  "Apple",
  "ASUS",
  "Audio-Technica",
  "Bang & Olufsen",
  "Beats",
  "Belkin",
  "Bose",
  "Canon",
  "Corsair",
  "Creative",
  "Dell",
  "DJI",
  "Epson",
  "Fitbit",
  "Garmin",
  "Google",
  "GoPro",
  "HP",
  "HTC",
  "Huawei",
  "Intel",
  "JBL",
  "LG",
  "Logitech",
  "Microsoft",
  "MSI",
  "Nikon",
  "Nintendo",
  "Nokia",
  "Nvidia",
  "OnePlus",
  "OPPO",
  "Panasonic",
  "Philips",
  "PlayStation",
  "Razer",
  "Samsung",
  "Sennheiser",
  "Sony",
  "Spotify",
  "Tesla",
  "Xiaomi",
  "Xbox",
  "Yamaha",
  // Beauty & Cosmetics Brands
  "Anastasia Beverly Hills",
  "Avon",
  "Benefit",
  "Bobbi Brown",
  "Charlotte Tilbury",
  "Clinique",
  "Covergirl",
  "Dior Beauty",
  "E.L.F.",
  "Estee Lauder",
  "Fenty Beauty",
  "Glossier",
  "Kylie Cosmetics",
  "L'Oreal",
  "Lancome",
  "Laura Mercier",
  "M.A.C",
  "Maybelline",
  "NARS",
  "NYX",
  "Rare Beauty",
  "Revlon",
  "Sephora",
  "Shiseido",
  "Tarte",
  "Too Faced",
  "Urban Decay",
  "Yves Saint Laurent Beauty",
  // Home & Furniture Brands
  "IKEA",
  "West Elm",
  "Pottery Barn",
  "Crate & Barrel",
  "Williams Sonoma",
  "CB2",
  "Room & Board",
  "Design Within Reach",
  "Herman Miller",
  "Knoll",
  "Steelcase",
  "Haworth",
  "Humanscale",
  "Muuto",
  "HAY",
  "Vitra",
  "Artek",
  "Alessi",
  "Kartell",
  "Cassina",
  "B&B Italia",
  "Poltrona Frau",
  "Roche Bobois",
  "Ligne Roset",
  "BoConcept",
  "Habitat",
  "John Lewis Home",
  "Zara Home",
  "H&M Home",
  "Maisons du Monde",
  "La Redoute",
  // Sports & Outdoor Brands
  "Nike",
  "Adidas",
  "Puma",
  "Under Armour",
  "Reebok",
  "New Balance",
  "ASICS",
  "Saucony",
  "Brooks",
  "Hoka",
  "On Running",
  "Salomon",
  "Merrell",
  "Columbia",
  "The North Face",
  "Patagonia",
  "Arc'teryx",
  "Mammut",
  "Outdoor Research",
  "Black Diamond",
  "Mountain Hardwear",
  "Marmot",
  "Fjällräven",
  "Haglöfs",
  "Peak Performance",
  "Norrøna",
  "Icebreaker",
  "Smartwool",
  "Minus33",
  "Ibex",
  // Fragrance Brands
  "Chanel Fragrance",
  "Dior Fragrance",
  "Tom Ford Fragrance",
  "Creed",
  "Byredo",
  "Le Labo",
  "Maison Margiela Fragrance",
  "Acqua di Parma",
  "Hermès Fragrance",
  "Jo Malone",
  "Diptyque",
  "L'Artisan Parfumeur",
  "Annick Goutal",
  "Penhaligon's",
  "Miller Harris",
  "Escentric Molecules",
  "Comme des Garcons Perfume",
  "Aesop Fragrance",
  "Kilian",
  "Bond No. 9",
  "Frederic Malle",
  "Serge Lutens",
  "Amouage",
  "Montale",
  "Mancera",
  "Nasomatto",
  "Ormonde Jayne",
  "Clive Christian",
  "Roja Parfums",
];
