/**
 * Food category and type data for restaurant food listings.
 * Follows the same class-based pattern as AllInOneCategoryData in productData.ts.
 */
export class FoodCategoryData {
    // ------------------------------------------------------
    // 1) Food Categories
    // ------------------------------------------------------
    static readonly kCategories: Array<{ key: string }> = [
      { key: "Kebabs & Grills" },
      { key: "Pide & Lahmacun" },
      { key: "Soups" },
      { key: "Salads" },
      { key: "Appetizers & Meze" },
      { key: "Stews & Casseroles" },
      { key: "Dolma & Sarma" },
      { key: "Steak & Roast" },
      { key: "Stir Fry & Wok" },
      { key: "Fried Chicken" },
      { key: "Rice & Pilaf" },
      { key: "Noodles" },
      { key: "Sushi & Sashimi" },
      { key: "Curry" },
      { key: "Pasta" },
      { key: "Wraps" },
      { key: "Doner" },
      { key: "Sandwich & Toast" },
      { key: "Seafood" },
      { key: "Breakfast" },
      { key: "Desserts & Pastry" },
      { key: "Beverages" },
      { key: "Hamburger" },
      { key: "Pizza" },
    ];
  
    // ------------------------------------------------------
    // 2) Food Types per Category
    // ------------------------------------------------------
    static readonly kFoodTypes: Record<string, string[]> = {
      "Kebabs & Grills": [
        "Adana Kebab",
        "Urfa Kebab",
        "Iskender Kebab",
        "Shish Kebab",
        "Chicken Kebab",
        "Kofte",
        "Mixed Grill",
        "Lamb Chops",
        "Beyti Kebab",
        "Ali Nazik",
        "Cop Sis",
        "Ciğer Kebab",
        "Tantuni",
        "Patlican Kebab",
        "Testi Kebab",
        "Cag Kebab",
        "Pideli Kofte",
        "Kuzu Sis",
        "Orman Kebab",
        "Yogurtlu Kebab",
        "Chelo Kebab",
        "Joojeh Kebab",
        "Koobideh",
        "Bulgogi",
        "Galbi",
        "Samgyeopsal",
        "Yakitori",
        "Tandoori Chicken",
        "Souvlaki",
        "Gyros",
        "Satay",
        "Kokoreç",
        "Other Kebab",
      ],
      "Pide & Lahmacun": [
        "Cheese Pide",
        "Minced Meat Pide",
        "Sucuklu Pide",
        "Kasarli Pide",
        "Kusbasi Pide",
        "Lahmacun",
        "Etli Ekmek",
        "Yumurtali Pide",
        "Ispanakli Pide",
        "Karisik Pide",
        "Pastirmali Pide",
        "Other Pide",
      ],
      Soups: [
        "Lentil Soup",
        "Tomato Soup",
        "Chicken Soup",
        "Tarhana Soup",
        "Ezogelin Soup",
        "Iskembe Soup",
        "Yayla Soup",
        "Mushroom Soup",
        "Mercimek Soup",
        "Beyran",
        "Dugun Corbasi",
        "Kellepaca Corbasi",
        "Sehriye Corbasi",
        "Lebeniye Corbasi",
        "Miso Soup",
        "Wonton Soup",
        "Kimchi Jjigae",
        "Sundubu Jjigae",
        "Ash Reshteh",
        "Minestrone",
        "Tom Yum",
        "Other Soup",
      ],
      Salads: [
        "Shepherd Salad",
        "Caesar Salad",
        "Greek Salad",
        "Seasonal Salad",
        "Rocket Salad",
        "Gavurdagi Salad",
        "Piyaz",
        "Coban Salad",
        "Kisir",
        "Semizotu Salatasi",
        "Mor Lahana Salatasi",
        "Fattoush",
        "Tabbouleh",
        "Caprese",
        "Other Salad",
      ],
      "Appetizers & Meze": [
        "Hummus",
        "Babaganoush",
        "Haydari",
        "Atom",
        "Acili Ezme",
        "Cacik",
        "Sigara Boregi",
        "Icli Kofte",
        "Mercimek Kofte",
        "Yaprak Sarma",
        "Falafel",
        "Mucver",
        "Patlican Soslu",
        "Cig Kofte",
        "Arnavut Cigeri",
        "Cerkez Tavugu",
        "Tarator",
        "Borek",
        "Su Boregi",
        "Dim Sum",
        "Spring Rolls",
        "Dumplings",
        "Gyoza",
        "Edamame",
        "Tempura",
        "Takoyaki",
        "Bruschetta",
        "Arancini",
        "Carpaccio",
        "Focaccia",
        "Kibbeh",
        "Moutabal",
        "Mirza Ghasemi",
        "Kashk-e Bademjan",
        "Pajeon",
        "Samosa",
        "Nachos",
        "Other Meze",
      ],
      "Stews & Casseroles": [
        "Guvec",
        "Moussaka",
        "Hunkar Begendi",
        "Etli Nohut",
        "Turlu",
        "Taze Fasulye",
        "Etli Bamya",
        "Etli Bezelye",
        "Etli Kapuska",
        "Ispanak Yemegi",
        "Etli Pirasa",
        "Kuru Fasulye",
        "Barbunya",
        "Nohut Yemegi",
        "Zeytinyagli Enginar",
        "Ghormeh Sabzi",
        "Fesenjan",
        "Dizi Abgoosht",
        "Hot Pot",
        "Mansaf",
        "Fatteh",
        "Maqluba",
        "Shakshuka",
        "Tteokbokki",
        "Osso Buco",
        "Kuzu Incik",
        "Other Stew",
      ],
      "Dolma & Sarma": [
        "Imam Bayildi",
        "Karniyarik",
        "Lahana Sarma",
        "Kabak Dolma",
        "Patlican Dolma",
        "Biber Dolma",
        "Etli Yaprak Sarma",
        "Zeytinyagli Dolma",
        "Stuffed Peppers",
        "Mahshi",
        "Other Dolma",
      ],
      "Steak & Roast": [
        "Steak",
        "Kuzu Tandir",
        "Sac Kavurma",
        "Tas Kebab",
        "Peking Duck",
        "Saltimbocca",
        "Other Steak",
      ],
      "Stir Fry & Wok": [
        "Kung Pao Chicken",
        "Sweet and Sour Chicken",
        "Mapo Tofu",
        "Teriyaki",
        "Dakgalbi",
        "Other Stir Fry",
      ],
      "Fried Chicken": [
        "Fried Chicken Classic",
        "Korean Fried Chicken",
        "Chicken Schnitzel",
        "Tonkatsu",
        "Chicken Wings",
        "Chicken Tenders",
        "Nuggets",
        "Other Fried Chicken",
      ],
      "Rice & Pilaf": [
        "Bulgur Pilaf",
        "Rice Pilaf",
        "Nohutlu Pilav",
        "Ic Pilav",
        "Domatesli Bulgur",
        "Firik Pilavi",
        "Sebzeli Pilav",
        "Meyhane Pilavi",
        "Fried Rice",
        "Bibimbap",
        "Donburi",
        "Tahdig",
        "Tahchin",
        "Zereshk Polo",
        "Baghali Polo",
        "Sabzi Polo",
        "Kabsa",
        "Machboos",
        "Biryani",
        "Hamsili Pilav",
        "Ali Pasa Pilavi",
        "Other Pilaf",
      ],
      Noodles: [
        "Ramen",
        "Udon",
        "Soba",
        "Pho",
        "Pad Thai",
        "Chow Mein",
        "Dan Dan Noodles",
        "Japchae",
        "Jajangmyeon",
        "Naengmyeon",
        "Other Noodle",
      ],
      "Sushi & Sashimi": [
        "Sushi",
        "Sashimi",
        "Maki Roll",
        "Nigiri",
        "Temaki",
        "Onigiri",
        "Kimbap",
        "Other Sushi",
      ],
      Curry: [
        "Katsu Curry",
        "Butter Chicken",
        "Tikka Masala",
        "Green Curry",
        "Red Curry",
        "Massaman Curry",
        "Dal",
        "Vindaloo",
        "Other Curry",
      ],
      Pasta: [
        "Spaghetti Bolognese",
        "Penne Arrabiata",
        "Fettuccine Alfredo",
        "Lasagna",
        "Makarna",
        "Carbonara",
        "Ravioli",
        "Risotto",
        "Gnocchi",
        "Manti",
        "Other Pasta",
      ],
      Wraps: [
        "Doner Wrap",
        "Tavuk Durum",
        "Et Durum",
        "Cig Kofte Durum",
        "Adana Durum",
        "Midye Durum",
        "Tacos",
        "Burrito",
        "Quesadilla",
        "Other Wrap",
      ],
      Doner: [
        "Chicken Doner",
        "Meat Doner",
        "Iskender Doner",
        "Tombik Doner",
        "Porsiyon Doner",
        "Shawarma",
        "Other Doner",
      ],
      "Sandwich & Toast": [
        "Tost",
        "Kasarli Tost",
        "Kumru",
        "Club Sandwich",
        "Panini",
        "Hot Dog",
        "French Fries",
        "Other Sandwich",
      ],
      Seafood: [
        "Grilled Fish",
        "Fried Calamari",
        "Shrimp Casserole",
        "Fish Sandwich",
        "Levrek",
        "Somon",
        "Hamsi",
        "Midye Tava",
        "Midye Dolma",
        "Karides Guvec",
        "Palamut",
        "Cipura",
        "Barbun Tava",
        "Lufer",
        "Fish and Chips",
        "Other Seafood",
      ],
      Breakfast: [
        "Turkish Breakfast Plate",
        "Serpme Kahvalti",
        "Menemen",
        "Sahanda Yumurta",
        "Sucuklu Yumurta",
        "Gozleme",
        "Simit",
        "Acma",
        "Pogaca",
        "Cilbir",
        "Pastirmali Yumurta",
        "Kaymak Bal",
        "Pisi",
        "Katmer Kahvalti",
        "Other Breakfast",
      ],
      "Desserts & Pastry": [
        "Baklava",
        "Kunefe",
        "Sutlac",
        "Kazandibi",
        "Tavuk Gogsu",
        "Asure",
        "Revani",
        "Lokma",
        "Trilece",
        "Profiterol",
        "Cheesecake",
        "Tiramisu",
        "Brownie",
        "Waffle",
        "Dondurma",
        "Gullac",
        "Keskul",
        "Tel Kadayif",
        "Sekerpare",
        "Tulumba",
        "Helva",
        "Katmer",
        "Kabak Tatlisi",
        "Ayva Tatlisi",
        "Sutlu Nuriye",
        "Burma Kadayif",
        "Panna Cotta",
        "Gelato",
        "Cannoli",
        "Knafeh",
        "Muhallabia",
        "Churros",
        "Mochi",
        "Other Dessert",
      ],
      Beverages: [
        "Turkish Tea",
        "Turkish Coffee",
        "Ayran",
        "Fresh Orange Juice",
        "Lemonade",
        "Smoothie",
        "Salgam",
        "Boza",
        "Sahlep",
        "Soft Drink",
        "Water",
        "Nar Suyu",
        "Serbet",
        "Turk Kahvesi Soguk",
        "Other Beverage",
      ],
      Hamburger: [
        "Hamburger",
        "Cheeseburger",
        "Chicken Burger",
        "Islak Hamburger",
        "Veggie Burger",
        "Other Hamburger",
      ],
      Pizza: [
        "Margarita Pizza",
        "Mixed Pizza",
        "Pepperoni Pizza",
        "Sucuklu Pizza",
        "Four Cheese Pizza",
        "Other Pizza",
      ],
    };
  
    // ------------------------------------------------------
    // 3) Category Translation Keys
    // ------------------------------------------------------
    static readonly kCategoryTranslationKeys: Record<string, string> = {
      "Kebabs & Grills": "foodCategoryKebabsGrills",
      "Pide & Lahmacun": "foodCategoryPideLahmacun",
      Soups: "foodCategorySoups",
      Salads: "foodCategorySalads",
      "Appetizers & Meze": "foodCategoryAppetizers",
      "Stews & Casseroles": "foodCategoryStews",
      "Dolma & Sarma": "foodCategoryDolma",
      "Steak & Roast": "foodCategorySteakRoast",
      "Stir Fry & Wok": "foodCategoryStirFry",
      "Fried Chicken": "foodCategoryFriedChicken",
      "Rice & Pilaf": "foodCategoryRicePilaf",
      Noodles: "foodCategoryNoodles",
      "Sushi & Sashimi": "foodCategorySushi",
      Curry: "foodCategoryCurry",
      Pasta: "foodCategoryPasta",
      Wraps: "foodCategoryWraps",
      Doner: "foodCategoryDoner",
      "Sandwich & Toast": "foodCategorySandwich",
      Seafood: "foodCategorySeafood",
      Breakfast: "foodCategoryBreakfast",
      "Desserts & Pastry": "foodCategoryDesserts",
      Beverages: "foodCategoryBeverages",
      Hamburger: "foodCategoryHamburger",
      Pizza: "foodCategoryPizza",
    };
  
    // ------------------------------------------------------
    // 4) Food Type Translation Keys
    // ------------------------------------------------------
    static readonly kFoodTypeTranslationKeys: Record<string, string> = {
      // Kebabs & Grills
      "Adana Kebab": "foodTypeAdanaKebab",
      "Urfa Kebab": "foodTypeUrfaKebab",
      "Iskender Kebab": "foodTypeIskenderKebab",
      "Shish Kebab": "foodTypeShishKebab",
      "Chicken Kebab": "foodTypeChickenKebab",
      Kofte: "foodTypeKofte",
      "Mixed Grill": "foodTypeMixedGrill",
      "Lamb Chops": "foodTypeLambChops",
      "Beyti Kebab": "foodTypeBeytiKebab",
      "Ali Nazik": "foodTypeAliNazik",
      "Cop Sis": "foodTypeCopSis",
      "Ciğer Kebab": "foodTypeCigerKebab",
      Tantuni: "foodTypeTantuni",
      "Patlican Kebab": "foodTypePatlicanKebab",
      "Testi Kebab": "foodTypeTestiKebab",
      "Cag Kebab": "foodTypeCagKebab",
      "Pideli Kofte": "foodTypePideliKofte",
      "Kuzu Sis": "foodTypeKuzuSis",
      "Orman Kebab": "foodTypeOrmanKebab",
      "Yogurtlu Kebab": "foodTypeYogurtluKebab",
      "Chelo Kebab": "foodTypeCheloKebab",
      "Joojeh Kebab": "foodTypeJoojehKebab",
      Koobideh: "foodTypeKoobideh",
      Bulgogi: "foodTypeBulgogi",
      Galbi: "foodTypeGalbi",
      Samgyeopsal: "foodTypeSamgyeopsal",
      Yakitori: "foodTypeYakitori",
      "Tandoori Chicken": "foodTypeTandooriChicken",
      Souvlaki: "foodTypeSouvlaki",
      Gyros: "foodTypeGyros",
      Satay: "foodTypeSatay",
      Kokoreç: "foodTypeKokorec",
      "Other Kebab": "foodTypeOtherKebab",
      // Pide & Lahmacun
      "Cheese Pide": "foodTypeCheesePide",
      "Minced Meat Pide": "foodTypeMincedMeatPide",
      "Sucuklu Pide": "foodTypeSucukluPide",
      "Kasarli Pide": "foodTypeKasarliPide",
      "Kusbasi Pide": "foodTypeKusbasiPide",
      Lahmacun: "foodTypeLahmacun",
      "Etli Ekmek": "foodTypeEtliEkmek",
      "Yumurtali Pide": "foodTypeYumurtaliPide",
      "Ispanakli Pide": "foodTypeIspanakliPide",
      "Karisik Pide": "foodTypeKarisikPide",
      "Pastirmali Pide": "foodTypePastirmaliPide",
      "Other Pide": "foodTypeOtherPide",
      // Soups
      "Lentil Soup": "foodTypeLentilSoup",
      "Tomato Soup": "foodTypeTomatoSoup",
      "Chicken Soup": "foodTypeChickenSoup",
      "Tarhana Soup": "foodTypeTarhanaSoup",
      "Ezogelin Soup": "foodTypeEzogelinSoup",
      "Iskembe Soup": "foodTypeIskembeSoup",
      "Yayla Soup": "foodTypeYaylaSoup",
      "Mushroom Soup": "foodTypeMushroomSoup",
      "Mercimek Soup": "foodTypeMercimekSoup",
      Beyran: "foodTypeBeyran",
      "Dugun Corbasi": "foodTypeDugunCorbasi",
      "Kellepaca Corbasi": "foodTypeKellepacaCorbasi",
      "Sehriye Corbasi": "foodTypeSehriyeCorbasi",
      "Lebeniye Corbasi": "foodTypeLebeniyeCorbasi",
      "Miso Soup": "foodTypeMisoSoup",
      "Wonton Soup": "foodTypeWontonSoup",
      "Kimchi Jjigae": "foodTypeKimchiJjigae",
      "Sundubu Jjigae": "foodTypeSundubuJjigae",
      "Ash Reshteh": "foodTypeAshReshteh",
      Minestrone: "foodTypeMinestrone",
      "Tom Yum": "foodTypeTomYum",
      "Other Soup": "foodTypeOtherSoup",
      // Salads
      "Shepherd Salad": "foodTypeShepherdSalad",
      "Caesar Salad": "foodTypeCaesarSalad",
      "Greek Salad": "foodTypeGreekSalad",
      "Seasonal Salad": "foodTypeSeasonalSalad",
      "Rocket Salad": "foodTypeRocketSalad",
      "Gavurdagi Salad": "foodTypeGavurdagiSalad",
      Piyaz: "foodTypePiyaz",
      "Coban Salad": "foodTypeCobanSalad",
      Kisir: "foodTypeKisir",
      "Semizotu Salatasi": "foodTypeSemizotuSalatasi",
      "Mor Lahana Salatasi": "foodTypeMorLahanaSalatasi",
      Fattoush: "foodTypeFattoush",
      Tabbouleh: "foodTypeTabbouleh",
      Caprese: "foodTypeCaprese",
      "Other Salad": "foodTypeOtherSalad",
      // Appetizers & Meze
      Hummus: "foodTypeHummus",
      Babaganoush: "foodTypeBabaganoush",
      Haydari: "foodTypeHaydari",
      Atom: "foodTypeAtom",
      "Acili Ezme": "foodTypeAciliEzme",
      Cacik: "foodTypeCacik",
      "Sigara Boregi": "foodTypeSigaraBoregi",
      "Icli Kofte": "foodTypeIcliKofte",
      "Mercimek Kofte": "foodTypeMercimekKofte",
      "Yaprak Sarma": "foodTypeYaprakSarma",
      Falafel: "foodTypeFalafel",
      Mucver: "foodTypeMucver",
      "Patlican Soslu": "foodTypePatlicanSoslu",
      "Cig Kofte": "foodTypeCigKofte",
      "Arnavut Cigeri": "foodTypeArnavutCigeri",
      "Cerkez Tavugu": "foodTypeCerkezTavugu",
      Tarator: "foodTypeTarator",
      Borek: "foodTypeBorek",
      "Su Boregi": "foodTypeSuBoregi",
      "Dim Sum": "foodTypeDimSum",
      "Spring Rolls": "foodTypeSpringRolls",
      Dumplings: "foodTypeDumplings",
      Gyoza: "foodTypeGyoza",
      Edamame: "foodTypeEdamame",
      Tempura: "foodTypeTempura",
      Takoyaki: "foodTypeTakoyaki",
      Bruschetta: "foodTypeBruschetta",
      Arancini: "foodTypeArancini",
      Carpaccio: "foodTypeCarpaccio",
      Focaccia: "foodTypeFocaccia",
      Kibbeh: "foodTypeKibbeh",
      Moutabal: "foodTypeMoutabal",
      "Mirza Ghasemi": "foodTypeMirzaGhasemi",
      "Kashk-e Bademjan": "foodTypeKashkBademjan",
      Pajeon: "foodTypePajeon",
      Samosa: "foodTypeSamosa",
      Nachos: "foodTypeNachos",
      "Other Meze": "foodTypeOtherMeze",
      // Stews & Casseroles
      Guvec: "foodTypeGuvec",
      Moussaka: "foodTypeMoussaka",
      "Hunkar Begendi": "foodTypeHunkarBegendi",
      "Etli Nohut": "foodTypeEtliNohut",
      Turlu: "foodTypeTurlu",
      "Taze Fasulye": "foodTypeTazeFasulye",
      "Etli Bamya": "foodTypeEtliBamya",
      "Etli Bezelye": "foodTypeEtliBezelye",
      "Etli Kapuska": "foodTypeEtliKapuska",
      "Ispanak Yemegi": "foodTypeIspanakYemegi",
      "Etli Pirasa": "foodTypeEtliPirasa",
      "Kuru Fasulye": "foodTypeKuruFasulye",
      Barbunya: "foodTypeBarbunya",
      "Nohut Yemegi": "foodTypeNohutYemegi",
      "Zeytinyagli Enginar": "foodTypeZeytinyagliEnginar",
      "Ghormeh Sabzi": "foodTypeGhormehSabzi",
      Fesenjan: "foodTypeFesenjan",
      "Dizi Abgoosht": "foodTypeDiziAbgoosht",
      "Hot Pot": "foodTypeHotPot",
      Mansaf: "foodTypeMansaf",
      Fatteh: "foodTypeFatteh",
      Maqluba: "foodTypeMaqluba",
      Shakshuka: "foodTypeShakshuka",
      Tteokbokki: "foodTypeTteokbokki",
      "Osso Buco": "foodTypeOssoBuco",
      "Kuzu Incik": "foodTypeKuzuIncik",
      "Other Stew": "foodTypeOtherStew",
      // Dolma & Sarma
      "Imam Bayildi": "foodTypeImamBayildi",
      Karniyarik: "foodTypeKarniyarik",
      "Lahana Sarma": "foodTypeLahanaSarma",
      "Kabak Dolma": "foodTypeKabakDolma",
      "Patlican Dolma": "foodTypePatlicanDolma",
      "Biber Dolma": "foodTypeBiberDolma",
      "Etli Yaprak Sarma": "foodTypeEtliYaprakSarma",
      "Zeytinyagli Dolma": "foodTypeZeytinyagliDolma",
      "Stuffed Peppers": "foodTypeStuffedPeppers",
      Mahshi: "foodTypeMahshi",
      "Other Dolma": "foodTypeOtherDolma",
      // Steak & Roast
      Steak: "foodTypeSteak",
      "Kuzu Tandir": "foodTypeKuzuTandir",
      "Sac Kavurma": "foodTypeSacKavurma",
      "Tas Kebab": "foodTypeTasKebab",
      "Peking Duck": "foodTypePekingDuck",
      Saltimbocca: "foodTypeSaltimbocca",
      "Other Steak": "foodTypeOtherSteak",
      // Stir Fry & Wok
      "Kung Pao Chicken": "foodTypeKungPaoChicken",
      "Sweet and Sour Chicken": "foodTypeSweetSourChicken",
      "Mapo Tofu": "foodTypeMapoTofu",
      Teriyaki: "foodTypeTeriyaki",
      Dakgalbi: "foodTypeDakgalbi",
      "Other Stir Fry": "foodTypeOtherStirFry",
      // Fried Chicken
      "Fried Chicken Classic": "foodTypeFriedChickenClassic",
      "Korean Fried Chicken": "foodTypeKoreanFriedChicken",
      "Chicken Schnitzel": "foodTypeChickenSchnitzel",
      Tonkatsu: "foodTypeTonkatsu",
      "Chicken Wings": "foodTypeChickenWings",
      "Chicken Tenders": "foodTypeChickenTenders",
      Nuggets: "foodTypeNuggets",
      "Other Fried Chicken": "foodTypeOtherFriedChicken",
      // Rice & Pilaf
      "Bulgur Pilaf": "foodTypeBulgurPilaf",
      "Rice Pilaf": "foodTypeRicePilaf",
      "Nohutlu Pilav": "foodTypeNohutluPilav",
      "Ic Pilav": "foodTypeIcPilav",
      "Domatesli Bulgur": "foodTypeDomatesliB",
      "Firik Pilavi": "foodTypeFirikPilavi",
      "Sebzeli Pilav": "foodTypeSebzeliPilav",
      "Meyhane Pilavi": "foodTypeMeyhanePilavi",
      "Fried Rice": "foodTypeFriedRice",
      Bibimbap: "foodTypeBibimbap",
      Donburi: "foodTypeDonburi",
      Tahdig: "foodTypeTahdig",
      Tahchin: "foodTypeTahchin",
      "Zereshk Polo": "foodTypeZereshkPolo",
      "Baghali Polo": "foodTypeBaghaliPolo",
      "Sabzi Polo": "foodTypeSabziPolo",
      Kabsa: "foodTypeKabsa",
      Machboos: "foodTypeMachboos",
      Biryani: "foodTypeBiryani",
      "Hamsili Pilav": "foodTypeHamsiliPilav",
      "Ali Pasa Pilavi": "foodTypeAliPasaPilavi",
      "Other Pilaf": "foodTypeOtherPilaf",
      // Noodles
      Ramen: "foodTypeRamen",
      Udon: "foodTypeUdon",
      Soba: "foodTypeSoba",
      Pho: "foodTypePho",
      "Pad Thai": "foodTypePadThai",
      "Chow Mein": "foodTypeChowMein",
      "Dan Dan Noodles": "foodTypeDanDanNoodles",
      Japchae: "foodTypeJapchae",
      Jajangmyeon: "foodTypeJajangmyeon",
      Naengmyeon: "foodTypeNaengmyeon",
      "Other Noodle": "foodTypeOtherNoodle",
      // Sushi & Sashimi
      Sushi: "foodTypeSushi",
      Sashimi: "foodTypeSashimi",
      "Maki Roll": "foodTypeMakiRoll",
      Nigiri: "foodTypeNigiri",
      Temaki: "foodTypeTemaki",
      Onigiri: "foodTypeOnigiri",
      Kimbap: "foodTypeKimbap",
      "Other Sushi": "foodTypeOtherSushi",
      // Curry
      "Katsu Curry": "foodTypeKatsuCurry",
      "Butter Chicken": "foodTypeButterChicken",
      "Tikka Masala": "foodTypeTikkaMasala",
      "Green Curry": "foodTypeGreenCurry",
      "Red Curry": "foodTypeRedCurry",
      "Massaman Curry": "foodTypeMassamanCurry",
      Dal: "foodTypeDal",
      Vindaloo: "foodTypeVindaloo",
      "Other Curry": "foodTypeOtherCurry",
      // Pasta
      "Spaghetti Bolognese": "foodTypeSpagBolognese",
      "Penne Arrabiata": "foodTypePenneArrabiata",
      "Fettuccine Alfredo": "foodTypeFettuccineAlfredo",
      Lasagna: "foodTypeLasagna",
      Makarna: "foodTypeMakarna",
      Carbonara: "foodTypeCarbonara",
      Ravioli: "foodTypeRavioli",
      Risotto: "foodTypeRisotto",
      Gnocchi: "foodTypeGnocchi",
      Manti: "foodTypeManti",
      "Other Pasta": "foodTypeOtherPasta",
      // Wraps
      "Doner Wrap": "foodTypeDonerWrap",
      "Tavuk Durum": "foodTypeTavukDurum",
      "Et Durum": "foodTypeEtDurum",
      "Cig Kofte Durum": "foodTypeCigKofteDurum",
      "Adana Durum": "foodTypeAdanaDurum",
      "Midye Durum": "foodTypeMidyeDurum",
      Tacos: "foodTypeTacos",
      Burrito: "foodTypeBurrito",
      Quesadilla: "foodTypeQuesadilla",
      "Other Wrap": "foodTypeOtherWrap",
      // Doner
      "Chicken Doner": "foodTypeChickenDoner",
      "Meat Doner": "foodTypeMeatDoner",
      "Iskender Doner": "foodTypeIskenderDoner",
      "Tombik Doner": "foodTypeTombikDoner",
      "Porsiyon Doner": "foodTypePorsiyonDoner",
      Shawarma: "foodTypeShawarma",
      "Other Doner": "foodTypeOtherDoner",
      // Sandwich & Toast
      Tost: "foodTypeTost",
      "Kasarli Tost": "foodTypeKasarliTost",
      Kumru: "foodTypeKumru",
      "Club Sandwich": "foodTypeClubSandwich",
      Panini: "foodTypePanini",
      "Hot Dog": "foodTypeHotDog",
      "French Fries": "foodTypeFrenchFries",
      "Other Sandwich": "foodTypeOtherSandwich",
      // Seafood
      "Grilled Fish": "foodTypeGrilledFish",
      "Fried Calamari": "foodTypeFriedCalamari",
      "Shrimp Casserole": "foodTypeShrimpCasserole",
      "Fish Sandwich": "foodTypeFishSandwich",
      Levrek: "foodTypeLevrek",
      Somon: "foodTypeSomon",
      Hamsi: "foodTypeHamsi",
      "Midye Tava": "foodTypeMidyeTava",
      "Midye Dolma": "foodTypeMidyeDolma",
      "Karides Guvec": "foodTypeKaridesGuvec",
      Palamut: "foodTypePalamut",
      Cipura: "foodTypeCipura",
      "Barbun Tava": "foodTypeBarbunTava",
      Lufer: "foodTypeLufer",
      "Fish and Chips": "foodTypeFishAndChips",
      "Other Seafood": "foodTypeOtherSeafood",
      // Breakfast
      "Turkish Breakfast Plate": "foodTypeTurkishBreakfast",
      "Serpme Kahvalti": "foodTypeSerpmeKahvalti",
      Menemen: "foodTypeMenemen",
      "Sahanda Yumurta": "foodTypeSahandaYumurta",
      "Sucuklu Yumurta": "foodTypeSucukluYumurta",
      Gozleme: "foodTypeGozleme",
      Simit: "foodTypeSimit",
      Acma: "foodTypeAcma",
      Pogaca: "foodTypePogaca",
      Cilbir: "foodTypeCilbir",
      "Pastirmali Yumurta": "foodTypePastirmaliYumurta",
      "Kaymak Bal": "foodTypeKaymakBal",
      Pisi: "foodTypePisi",
      "Katmer Kahvalti": "foodTypeKatmerKahvalti",
      "Other Breakfast": "foodTypeOtherBreakfast",
      // Desserts & Pastry
      Baklava: "foodTypeBaklava",
      Kunefe: "foodTypeKunefe",
      Sutlac: "foodTypeSutlac",
      Kazandibi: "foodTypeKazandibi",
      "Tavuk Gogsu": "foodTypeTavukGogsu",
      Asure: "foodTypeAsure",
      Revani: "foodTypeRevani",
      Lokma: "foodTypeLokma",
      Trilece: "foodTypeTrilece",
      Profiterol: "foodTypeProfiterol",
      Cheesecake: "foodTypeCheesecake",
      Tiramisu: "foodTypeTiramisu",
      Brownie: "foodTypeBrownie",
      Waffle: "foodTypeWaffle",
      Dondurma: "foodTypeDondurma",
      Gullac: "foodTypeGullac",
      Keskul: "foodTypeKeskul",
      "Tel Kadayif": "foodTypeTelKadayif",
      Sekerpare: "foodTypeSekerpare",
      Tulumba: "foodTypeTulumba",
      Helva: "foodTypeHelva",
      Katmer: "foodTypeKatmer",
      "Kabak Tatlisi": "foodTypeKabakTatlisi",
      "Ayva Tatlisi": "foodTypeAyvaTatlisi",
      "Sutlu Nuriye": "foodTypeSutluNuriye",
      "Burma Kadayif": "foodTypeBurmaKadayif",
      "Panna Cotta": "foodTypePannaCotta",
      Gelato: "foodTypeGelato",
      Cannoli: "foodTypeCannoli",
      Knafeh: "foodTypeKnafeh",
      Muhallabia: "foodTypeMuhallabia",
      Churros: "foodTypeChurros",
      Mochi: "foodTypeMochi",
      "Other Dessert": "foodTypeOtherDessert",
      // Beverages
      "Turkish Tea": "foodTypeTurkishTea",
      "Turkish Coffee": "foodTypeTurkishCoffee",
      Ayran: "foodTypeAyran",
      "Fresh Orange Juice": "foodTypeFreshOrangeJuice",
      Lemonade: "foodTypeLemonade",
      Smoothie: "foodTypeSmoothie",
      Salgam: "foodTypeSalgam",
      Boza: "foodTypeBoza",
      Sahlep: "foodTypeSahlep",
      "Soft Drink": "foodTypeSoftDrink",
      Water: "foodTypeWater",
      "Nar Suyu": "foodTypeNarSuyu",
      Serbet: "foodTypeSerbet",
      "Turk Kahvesi Soguk": "foodTypeTurkKahvesiSoguk",
      "Other Beverage": "foodTypeOtherBeverage",
      // Hamburger
      Hamburger: "foodTypeHamburger",
      Cheeseburger: "foodTypeCheeseburger",
      "Chicken Burger": "foodTypeChickenBurger",
      "Islak Hamburger": "foodTypeIslakHamburger",
      "Veggie Burger": "foodTypeVeggieBurger",
      "Other Hamburger": "foodTypeOtherHamburger",
      // Pizza
      "Margarita Pizza": "foodTypeMargaritaPizza",
      "Mixed Pizza": "foodTypeMixedPizza",
      "Pepperoni Pizza": "foodTypePepperoniPizza",
      "Sucuklu Pizza": "foodTypeSucukluPizza",
      "Four Cheese Pizza": "foodTypeFourCheesePizza",
      "Other Pizza": "foodTypeOtherPizza",
    };
  }
  