// Categories (Product-Based)
export const categories = [
  { key: "Clothing & Fashion", image: "clothing_fashion.jpg" },
  { key: "Footwear", image: "footwear.jpg" },
  { key: "Accessories", image: "accessories.jpg" },
  { key: "Mother & Child", image: "mother_child.jpg" },
  { key: "Home & Furniture", image: "home_furniture.jpg" },
  { key: "Beauty & Personal Care", image: "beauty_personal_care.jpg" },
  { key: "Bags & Luggage", image: "bags_luggage.jpg" },
  { key: "Electronics", image: "electronics.jpg" },
  { key: "Sports & Outdoor", image: "sports_outdoor.jpg" },
  { key: "Books, Stationery & Hobby", image: "books_stationery_hobby.jpg" },
  { key: "Tools & Hardware", image: "tools_hardware.jpg" },
  { key: "Pet Supplies", image: "pet_supplies.jpg" },
  { key: "Automotive", image: "automotive.jpg" },
  { key: "Health & Wellness", image: "health_wellness.jpg" },
];

// Category Keywords
export const categoryKeywordsMap: Record<string, string[]> = {
  "Clothing & Fashion": [
    "clothing",
    "apparel",
    "fashion",
    "garments",
    "wear",
    "dress",
    "shirt",
    "pants",
    "underwear",
    "sleepwear",
    "sportswear",
    "swimwear",
  ],
  Footwear: [
    "shoes",
    "boots",
    "sneakers",
    "sandals",
    "heels",
    "footwear",
    "athletic shoes",
    "dress shoes",
    "casual shoes",
  ],
  Accessories: [
    "jewelry",
    "watches",
    "belts",
    "scarves",
    "hats",
    "gloves",
    "sunglasses",
    "ties",
    "cufflinks",
  ],
  "Mother & Child": [
    "baby",
    "kids",
    "children",
    "infant",
    "toddler",
    "maternity",
    "pregnancy",
    "toys",
    "baby care",
    "feeding",
    "safety",
    "strollers",
  ],
  "Home & Furniture": [
    "furniture",
    "home decor",
    "bedding",
    "kitchen",
    "bathroom",
    "lighting",
    "storage",
    "textiles",
    "appliances",
  ],
  "Beauty & Personal Care": [
    "skincare",
    "makeup",
    "cosmetics",
    "haircare",
    "fragrances",
    "personal care",
    "nail care",
    "body care",
    "grooming",
  ],
  "Bags & Luggage": [
    "bags",
    "handbags",
    "backpacks",
    "purses",
    "wallets",
    "luggage",
    "suitcases",
    "travel bags",
    "briefcases",
  ],
  Electronics: [
    "electronics",
    "gadgets",
    "smartphones",
    "computers",
    "laptops",
    "tablets",
    "headphones",
    "cameras",
    "televisions",
    "gaming",
    "smart devices",
  ],
  "Sports & Outdoor": [
    "sports",
    "fitness",
    "outdoor",
    "exercise",
    "camping",
    "hiking",
    "cycling",
    "running",
    "gym",
    "athletic",
  ],
  "Books, Stationery & Hobby": [
    "books",
    "stationery",
    "office supplies",
    "art supplies",
    "crafting",
    "hobby",
    "educational",
    "writing",
    "paper",
  ],
  "Tools & Hardware": [
    "tools",
    "hardware",
    "construction",
    "repair",
    "maintenance",
    "plumbing",
    "electrical",
    "automotive tools",
    "safety equipment",
  ],
  "Pet Supplies": [
    "dog supplies",
    "cat supplies",
    "bird supplies",
    "fish supplies",
    "small animals",
    "pet food",
    "pet care",
    "pet accessories",
  ],
  Automotive: [
    "car parts",
    "auto accessories",
    "car care",
    "automotive tools",
    "tires",
    "car electronics",
    "motor oil",
    "car maintenance",
  ],
  "Health & Wellness": [
    "vitamins",
    "supplements",
    "medical supplies",
    "fitness equipment",
    "health monitors",
    "wellness products",
    "first aid",
    "mobility aids",
  ],
};

// Subcategories
export const subcategoriesMap: Record<string, string[]> = {
  "Clothing & Fashion": [
    "Dresses",
    "Tops & Shirts",
    "Bottoms",
    "Outerwear",
    "Underwear & Sleepwear",
    "Swimwear",
    "Activewear",
    "Suits & Formal",
    "Traditional & Cultural",
  ],
  Footwear: [
    "Sneakers & Athletic",
    "Casual Shoes",
    "Formal Shoes",
    "Boots",
    "Sandals & Flip-Flops",
    "Slippers",
    "Specialized Footwear",
  ],
  Accessories: [
    "Jewelry",
    "Watches",
    "Belts",
    "Hats & Caps",
    "Scarves & Wraps",
    "Sunglasses & Eyewear",
    "Gloves",
    "Hair Accessories",
    "Other Accessories",
  ],
  "Mother & Child": [
    "Baby Clothing",
    "Kids Clothing",
    "Kids Footwear",
    "Toys & Games",
    "Baby Care",
    "Maternity",
    "Strollers & Car Seats",
    "Feeding & Nursing",
    "Safety & Security",
    "Educational",
  ],
  "Home & Furniture": [
    "Living Room Furniture",
    "Bedroom Furniture",
    "Kitchen & Dining",
    "Bathroom",
    "Home Decor",
    "Lighting",
    "Storage & Organization",
    "Textiles & Soft Furnishing",
    "Garden & Outdoor",
  ],
  "Beauty & Personal Care": [
    "Skincare",
    "Makeup",
    "Haircare",
    "Fragrances",
    "Personal Hygiene",
    "Nail Care",
    "Body Care",
    "Oral Care",
    "Beauty Tools & Accessories",
  ],
  "Bags & Luggage": [
    "Handbags",
    "Backpacks",
    "Travel Luggage",
    "Briefcases & Business Bags",
    "Sports & Gym Bags",
    "Wallets & Small Accessories",
    "Specialty Bags",
  ],
  Electronics: [
    "Smartphones & Accessories",
    "Computers & Laptops",
    "TVs & Home Entertainment",
    "Audio Equipment",
    "Gaming",
    "Smart Home & IoT",
    "Cameras & Photography",
    "Wearable Tech",
    "Home Appliances",
    "Personal Care Electronics",
  ],
  "Sports & Outdoor": [
    "Fitness & Exercise",
    "Sports",
    "Water Sports",
    "Outdoor & Camping",
    "Winter Sports",
    "Cycling",
    "Running & Athletics",
    "Sports Accessories",
    "Sportswear",
  ],
  "Books, Stationery & Hobby": [
    "Books & Literature",
    "Office & School Supplies",
    "Art & Craft Supplies",
    "Writing Instruments",
    "Paper Products",
    "Educational Materials",
    "Hobbies & Collections",
    "Musical Instruments",
  ],
  "Tools & Hardware": [
    "Hand Tools",
    "Power Tools",
    "Hardware & Fasteners",
    "Electrical Supplies",
    "Plumbing Supplies",
    "Building Materials",
    "Safety Equipment",
    "Measuring Tools",
    "Tool Storage",
  ],
  "Pet Supplies": [
    "Dog Supplies",
    "Cat Supplies",
    "Bird Supplies",
    "Fish & Aquarium",
    "Small Animal Supplies",
    "Pet Food & Treats",
    "Pet Care & Health",
    "Pet Accessories",
    "Pet Training",
  ],
  Automotive: [
    "Car Parts & Components",
    "Car Electronics",
    "Car Care & Maintenance",
    "Tires & Wheels",
    "Interior Accessories",
    "Exterior Accessories",
    "Tools & Equipment",
    "Motorcycle Parts",
  ],
  "Health & Wellness": [
    "Vitamins & Supplements",
    "Medical Equipment",
    "First Aid & Safety",
    "Fitness & Exercise Equipment",
    "Health Monitoring",
    "Mobility & Daily Living",
    "Alternative Medicine",
    "Personal Care",
  ],
};

// Sub-subcategories
export const subSubcategoriesMap: Record<string, Record<string, string[]>> = {
  "Clothing & Fashion": {
    Dresses: [
      "Casual Dresses",
      "Formal Dresses",
      "Evening Gowns",
      "Cocktail Dresses",
      "Maxi Dresses",
      "Mini Dresses",
      "Midi Dresses",
      "Wedding Dresses",
      "Sundresses",
    ],
    "Tops & Shirts": [
      "T-Shirts",
      "Shirts",
      "Blouses",
      "Tank Tops",
      "Polo Shirts",
      "Crop Tops",
      "Tunics",
      "Hoodies",
      "Sweatshirts",
    ],
    Bottoms: [
      "Jeans",
      "Pants",
      "Shorts",
      "Skirts",
      "Leggings",
      "Joggers",
      "Capris",
      "Culottes",
    ],
    Outerwear: [
      "Jackets",
      "Coats",
      "Blazers",
      "Cardigans",
      "Sweaters",
      "Vests",
      "Parkas",
      "Trench Coats",
      "Windbreakers",
    ],
    "Underwear & Sleepwear": [
      "Bras",
      "Panties",
      "Boxers",
      "Briefs",
      "Undershirts",
      "Sleepwear",
      "Pajamas",
      "Nightgowns",
      "Robes",
      "Socks",
      "Tights",
    ],
    Swimwear: [
      "Bikinis",
      "One-Piece Swimsuits",
      "Swim Shorts",
      "Boardshorts",
      "Cover-Ups",
      "Rashguards",
    ],
    Activewear: [
      "Sports Bras",
      "Athletic Tops",
      "Athletic Bottoms",
      "Tracksuits",
      "Yoga Wear",
      "Running Gear",
      "Gym Wear",
    ],
    "Suits & Formal": [
      "Business Suits",
      "Tuxedos",
      "Formal Shirts",
      "Dress Pants",
      "Waistcoats",
      "Bow Ties",
      "Cufflinks",
    ],
    "Traditional & Cultural": [
      "Ethnic Wear",
      "Cultural Costumes",
      "Traditional Dresses",
      "Ceremonial Clothing",
    ],
  },
  Footwear: {
    "Sneakers & Athletic": [
      "Running Shoes",
      "Basketball Shoes",
      "Training Shoes",
      "Casual Sneakers",
      "Skateboard Shoes",
      "Tennis Shoes",
      "Walking Shoes",
    ],
    "Casual Shoes": [
      "Loafers",
      "Boat Shoes",
      "Canvas Shoes",
      "Slip-On Shoes",
      "Espadrilles",
      "Moccasins",
    ],
    "Formal Shoes": [
      "Dress Shoes",
      "Oxford Shoes",
      "Derby Shoes",
      "Monk Strap Shoes",
      "Pumps",
      "High Heels",
      "Flats",
    ],
    Boots: [
      "Ankle Boots",
      "Knee-High Boots",
      "Combat Boots",
      "Chelsea Boots",
      "Work Boots",
      "Hiking Boots",
      "Rain Boots",
      "Snow Boots",
    ],
    "Sandals & Flip-Flops": [
      "Flip-Flops",
      "Flat Sandals",
      "Heeled Sandals",
      "Sport Sandals",
      "Slides",
      "Gladiator Sandals",
    ],
    Slippers: [
      "House Slippers",
      "Bedroom Slippers",
      "Moccasin Slippers",
      "Slipper Boots",
    ],
    "Specialized Footwear": [
      "Safety Shoes",
      "Medical Shoes",
      "Dance Shoes",
      "Cleats",
      "Climbing Shoes",
    ],
  },
  Accessories: {
    Jewelry: [
      "Necklaces",
      "Earrings",
      "Rings",
      "Bracelets",
      "Anklets",
      "Brooches",
      "Jewelry Sets",
      "Body Jewelry",
    ],
    Watches: [
      "Analog Watches",
      "Digital Watches",
      "Smartwatches",
      "Sports Watches",
      "Luxury Watches",
      "Fashion Watches",
      "Kids Watches",
    ],
    Belts: [
      "Leather Belts",
      "Fabric Belts",
      "Chain Belts",
      "Dress Belts",
      "Casual Belts",
      "Designer Belts",
    ],
    "Hats & Caps": [
      "Baseball Caps",
      "Beanies",
      "Fedoras",
      "Sun Hats",
      "Bucket Hats",
      "Berets",
      "Snapbacks",
    ],
    "Scarves & Wraps": [
      "Silk Scarves",
      "Winter Scarves",
      "Shawls",
      "Pashminas",
      "Bandanas",
      "Wraps",
    ],
    "Sunglasses & Eyewear": [
      "Sunglasses",
      "Reading Glasses",
      "Blue Light Glasses",
      "Safety Glasses",
      "Fashion Glasses",
    ],
    Gloves: [
      "Winter Gloves",
      "Dress Gloves",
      "Work Gloves",
      "Sports Gloves",
      "Touchscreen Gloves",
    ],
    "Hair Accessories": [
      "Hair Clips",
      "Headbands",
      "Hair Ties",
      "Bobby Pins",
      "Hair Scarves",
      "Hair Jewelry",
    ],
    "Other Accessories": [
      "Keychains",
      "Phone Cases",
      "Wallets",
      "Purse Accessories",
      "Pins & Badges",
    ],
  },
  "Mother & Child": {
    "Baby Clothing": [
      "Bodysuits",
      "Rompers",
      "Baby Sets",
      "Baby Sleepwear",
      "Baby Socks",
      "Baby Hats",
      "Baby Mittens",
    ],
    "Kids Clothing": [
      "Kids T-Shirts",
      "Kids Pants",
      "Kids Dresses",
      "Kids Sweatshirts",
      "Kids Jackets",
      "Kids Pajamas",
      "School Uniforms",
    ],
    "Kids Footwear": [
      "Kids Sneakers",
      "Kids Sandals",
      "Kids Boots",
      "School Shoes",
      "Sports Shoes",
      "Rain Boots",
      "Kids Slippers",
    ],
    "Toys & Games": [
      "Educational Toys",
      "Plush Toys",
      "Building Blocks",
      "Dolls & Action Figures",
      "Puzzles",
      "Board Games",
      "Electronic Toys",
      "Outdoor Play",
    ],
    "Baby Care": [
      "Diapers",
      "Baby Wipes",
      "Baby Skincare",
      "Baby Bath Products",
      "Baby Health",
      "Baby Monitors",
    ],
    Maternity: [
      "Maternity Clothing",
      "Nursing Bras",
      "Maternity Accessories",
      "Pregnancy Support",
    ],
    "Strollers & Car Seats": [
      "Strollers",
      "Car Seats",
      "Travel Systems",
      "Booster Seats",
      "Stroller Accessories",
    ],
    "Feeding & Nursing": [
      "Baby Bottles",
      "Breast Pumps",
      "Pacifiers",
      "High Chairs",
      "Feeding Accessories",
      "Baby Food",
    ],
    "Safety & Security": [
      "Baby Gates",
      "Outlet Covers",
      "Cabinet Locks",
      "Corner Guards",
      "Baby Monitors",
    ],
    Educational: [
      "Learning Toys",
      "Educational Books",
      "Flash Cards",
      "Science Kits",
      "Musical Instruments",
    ],
  },
  "Home & Furniture": {
    "Living Room Furniture": [
      "Sofas",
      "Armchairs",
      "Coffee Tables",
      "TV Stands",
      "Bookcases",
      "Side Tables",
      "Ottoman",
      "Recliners",
    ],
    "Bedroom Furniture": [
      "Beds",
      "Mattresses",
      "Wardrobes",
      "Dressers",
      "Nightstands",
      "Mirrors",
      "Bed Frames",
      "Headboards",
    ],
    "Kitchen & Dining": [
      "Dining Tables",
      "Dining Chairs",
      "Bar Stools",
      "Kitchen Islands",
      "Cookware",
      "Dinnerware",
      "Glassware",
      "Kitchen Appliances",
      "Utensils",
    ],
    Bathroom: [
      "Bathroom Vanities",
      "Shower Curtains",
      "Bath Mats",
      "Towel Racks",
      "Bathroom Storage",
      "Mirrors",
      "Accessories",
    ],
    "Home Decor": [
      "Wall Art",
      "Decorative Objects",
      "Candles",
      "Vases",
      "Picture Frames",
      "Clocks",
      "Artificial Plants",
      "Sculptures",
    ],
    Lighting: [
      "Ceiling Lights",
      "Table Lamps",
      "Floor Lamps",
      "Wall Lights",
      "Pendant Lights",
      "Chandelier",
      "String Lights",
      "Night Lights",
    ],
    "Storage & Organization": [
      "Shelving Units",
      "Storage Boxes",
      "Baskets",
      "Hangers",
      "Closet Organizers",
      "Drawer Organizers",
      "Storage Bins",
    ],
    "Textiles & Soft Furnishing": [
      "Curtains",
      "Blinds",
      "Rugs",
      "Cushions",
      "Throws",
      "Bed Linens",
      "Towels",
      "Blankets",
    ],
    "Garden & Outdoor": [
      "Garden Furniture",
      "Plant Pots",
      "Garden Tools",
      "Outdoor Lighting",
      "BBQ & Grills",
      "Umbrellas",
      "Garden Decor",
    ],
  },
  "Beauty & Personal Care": {
    Skincare: [
      "Cleansers",
      "Moisturizers",
      "Serums",
      "Face Masks",
      "Sunscreen",
      "Toners",
      "Eye Creams",
      "Anti-Aging",
      "Acne Treatment",
    ],
    Makeup: [
      "Foundation",
      "Concealer",
      "Powder",
      "Blush",
      "Bronzer",
      "Highlighter",
      "Eyeshadow",
      "Eyeliner",
      "Mascara",
      "Lipstick",
      "Lip Gloss",
      "Makeup Brushes",
    ],
    Haircare: [
      "Shampoo",
      "Conditioner",
      "Hair Masks",
      "Hair Oils",
      "Styling Products",
      "Hair Color",
      "Hair Tools",
    ],
    Fragrances: [
      "Perfumes",
      "Eau de Toilette",
      "Body Sprays",
      "Deodorants",
      "Cologne",
      "Essential Oils",
    ],
    "Personal Hygiene": [
      "Body Wash",
      "Soap",
      "Shampoo",
      "Deodorants",
      "Feminine Care",
      "Men's Grooming",
      "Intimate Care",
    ],
    "Nail Care": [
      "Nail Polish",
      "Nail Tools",
      "Nail Treatments",
      "Nail Art",
      "Cuticle Care",
      "Nail Files",
    ],
    "Body Care": [
      "Body Lotions",
      "Body Oils",
      "Body Scrubs",
      "Hand Cream",
      "Foot Care",
      "Bath Products",
      "Massage Oils",
    ],
    "Oral Care": [
      "Toothbrushes",
      "Toothpaste",
      "Mouthwash",
      "Dental Floss",
      "Teeth Whitening",
      "Oral Health",
    ],
    "Beauty Tools & Accessories": [
      "Makeup Brushes",
      "Beauty Sponges",
      "Hair Brushes",
      "Mirrors",
      "Tweezers",
      "Nail Clippers",
      "Beauty Cases",
    ],
  },
  "Bags & Luggage": {
    Handbags: [
      "Tote Bags",
      "Shoulder Bags",
      "Crossbody Bags",
      "Clutches",
      "Evening Bags",
      "Satchels",
      "Hobo Bags",
    ],
    Backpacks: [
      "School Backpacks",
      "Travel Backpacks",
      "Laptop Backpacks",
      "Hiking Backpacks",
      "Casual Backpacks",
      "Kids Backpacks",
    ],
    "Travel Luggage": [
      "Suitcases",
      "Carry-On Bags",
      "Travel Duffel Bags",
      "Luggage Sets",
      "Garment Bags",
      "Travel Accessories",
    ],
    "Briefcases & Business Bags": [
      "Briefcases",
      "Laptop Bags",
      "Messenger Bags",
      "Portfolio Bags",
      "Business Totes",
    ],
    "Sports & Gym Bags": [
      "Gym Bags",
      "Sports Duffel Bags",
      "Equipment Bags",
      "Yoga Bags",
      "Swimming Bags",
    ],
    "Wallets & Small Accessories": [
      "Wallets",
      "Card Holders",
      "Coin Purses",
      "Key Cases",
      "Phone Cases",
      "Passport Holders",
    ],
    "Specialty Bags": [
      "Camera Bags",
      "Diaper Bags",
      "Lunch Bags",
      "Tool Bags",
      "Cosmetic Bags",
      "Beach Bags",
    ],
  },
  Electronics: {
    "Smartphones & Accessories": [
      "Smartphones",
      "Phone Cases",
      "Screen Protectors",
      "Chargers",
      "Power Banks",
      "Phone Stands",
      "Wireless Chargers",
    ],
    "Computers & Laptops": [
      "Laptops",
      "Desktop Computers",
      "Tablets",
      "Monitors",
      "Keyboards",
      "Mice",
      "Laptop Accessories",
      "Computer Components",
    ],
    "TVs & Home Entertainment": [
      "Smart TVs",
      "Projectors",
      "Streaming Devices",
      "TV Mounts & Stands",
      "Home Theater Systems",
      "TV Cables & Accessories",
      "Remote Controls",
      "TV Antennas",
      "Media Players",
    ],
    "Audio Equipment": [
      "Headphones",
      "Earbuds",
      "Speakers",
      "Sound Systems",
      "Soundbars",
      "Microphones",
      "Amplifiers",
      "Turntables",
      "Audio Cables",
    ],
    Gaming: [
      "Gaming Consoles",
      "Video Games",
      "Gaming Controllers",
      "Gaming Headsets",
      "Gaming Chairs",
      "VR Headsets",
      "Gaming Accessories",
    ],
    "Smart Home & IoT": [
      "Smart Speakers",
      "Smart Lights",
      "Smart Plugs",
      "Security Cameras",
      "Smart Thermostats",
      "Smart Locks",
      "Home Automation",
    ],
    "Cameras & Photography": [
      "Digital Cameras",
      "DSLR Cameras",
      "Action Cameras",
      "Camera Lenses",
      "Tripods",
      "Camera Accessories",
      "Photography Equipment",
    ],
    "Wearable Tech": [
      "Smartwatches",
      "Fitness Trackers",
      "Smart Glasses",
      "Health Monitors",
      "Wearable Accessories",
    ],
    "Home Appliances": [
      "Kitchen Appliances",
      "Laundry Appliances",
      "Cleaning Appliances",
      "Air Conditioning",
      "Heating",
      "Small Appliances",
    ],
    "Personal Care Electronics": [
      "Hair Dryers",
      "Hair Straighteners",
      "Electric Shavers",
      "Toothbrushes",
      "Beauty Devices",
      "Health Monitors",
    ],
  },
  "Sports & Outdoor": {
    "Fitness & Exercise": [
      "Cardio Equipment",
      "Strength Training",
      "Yoga Equipment",
      "Pilates Equipment",
      "Home Gym",
      "Exercise Accessories",
      "Recovery Equipment",
    ],
    Sports: [
      "Football",
      "Basketball",
      "Baseball",
      "Volleyball",
      "Tennis",
      "Cricket",
      "American Football",
      "Golf",
      "Table Tennis",
      "Badminton",
    ],
    "Water Sports": [
      "Swimming",
      "Surfing",
      "Kayaking",
      "Diving",
      "Water Skiing",
      "Fishing",
      "Boating",
      "Water Safety",
    ],
    "Outdoor & Camping": [
      "Camping Gear",
      "Hiking Equipment",
      "Backpacking",
      "Climbing Gear",
      "Outdoor Clothing",
      "Navigation",
      "Survival Gear",
    ],
    "Winter Sports": [
      "Skiing",
      "Snowboarding",
      "Ice Skating",
      "Winter Clothing",
      "Snow Equipment",
      "Winter Accessories",
    ],
    Cycling: [
      "Bicycles",
      "Bike Accessories",
      "Cycling Apparel",
      "Bike Maintenance",
      "Bike Safety",
      "E-Bikes",
    ],
    "Running & Athletics": [
      "Running Shoes",
      "Running Apparel",
      "Track & Field",
      "Marathon Gear",
      "Running Accessories",
      "Performance Monitoring",
    ],
    "Sports Accessories": [
      "Sports Bags",
      "Protective Gear",
      "Sports Nutrition",
      "Hydration",
      "Sports Technology",
      "Fan Gear",
    ],
    Sportswear: [
      "Athletic Tops",
      "Athletic Bottoms",
      "Sports Bras",
      "Athletic Shoes",
      "Sports Accessories",
      "Team Jerseys",
    ],
  },
  "Books, Stationery & Hobby": {
    "Books & Literature": [
      "Fiction Books",
      "Non-Fiction Books",
      "Educational Books",
      "Children's Books",
      "Reference Books",
      "Magazines",
      "Comics",
      "E-Books",
    ],
    "Office & School Supplies": [
      "Notebooks",
      "Binders",
      "Folders",
      "Desk Accessories",
      "Calculators",
      "Labels",
      "Staplers",
      "Organizers",
    ],
    "Art & Craft Supplies": [
      "Drawing Supplies",
      "Painting Supplies",
      "Craft Materials",
      "Scrapbooking",
      "Sewing Supplies",
      "Jewelry Making",
      "Model Building",
    ],
    "Writing Instruments": [
      "Pens",
      "Pencils",
      "Markers",
      "Highlighters",
      "Fountain Pens",
      "Mechanical Pencils",
      "Erasers",
    ],
    "Paper Products": [
      "Copy Paper",
      "Specialty Paper",
      "Cardstock",
      "Envelopes",
      "Sticky Notes",
      "Index Cards",
      "Construction Paper",
    ],
    "Educational Materials": [
      "Learning Games",
      "Flash Cards",
      "Educational Toys",
      "Science Kits",
      "Math Tools",
      "Language Learning",
    ],
    "Hobbies & Collections": [
      "Board Games",
      "Puzzles",
      "Trading Cards",
      "Collectibles",
      "Model Kits",
      "Gaming Accessories",
    ],
    "Musical Instruments": [
      "String Instruments",
      "Wind Instruments",
      "Percussion",
      "Electronic Instruments",
      "Music Accessories",
      "Sheet Music",
    ],
  },
  "Tools & Hardware": {
    "Hand Tools": [
      "Hammers",
      "Screwdrivers",
      "Wrenches",
      "Pliers",
      "Saws",
      "Chisels",
      "Utility Knives",
      "Hand Tool Sets",
    ],
    "Power Tools": [
      "Drills",
      "Saws",
      "Sanders",
      "Grinders",
      "Routers",
      "Nail Guns",
      "Impact Drivers",
      "Multi-Tools",
    ],
    "Hardware & Fasteners": [
      "Screws",
      "Bolts & Nuts",
      "Nails",
      "Washers",
      "Anchors",
      "Hinges",
      "Handles & Knobs",
      "Chains",
    ],
    "Electrical Supplies": [
      "Wire & Cable",
      "Outlets & Switches",
      "Circuit Breakers",
      "Light Fixtures",
      "Electrical Tools",
      "Extension Cords",
    ],
    "Plumbing Supplies": [
      "Pipes & Fittings",
      "Valves",
      "Faucets",
      "Toilet Parts",
      "Drain Cleaners",
      "Pipe Tools",
      "Sealants",
    ],
    "Building Materials": [
      "Lumber",
      "Drywall",
      "Insulation",
      "Roofing Materials",
      "Flooring",
      "Concrete",
      "Paint",
    ],
    "Safety Equipment": [
      "Work Gloves",
      "Safety Glasses",
      "Hard Hats",
      "Ear Protection",
      "Respirators",
      "Safety Vests",
      "First Aid Kits",
    ],
    "Measuring Tools": [
      "Tape Measures",
      "Levels",
      "Squares",
      "Calipers",
      "Rulers",
      "Laser Levels",
      "Marking Tools",
    ],
    "Tool Storage": [
      "Tool Boxes",
      "Tool Bags",
      "Tool Chests",
      "Workshop Storage",
      "Tool Organizers",
    ],
  },
  "Pet Supplies": {
    "Dog Supplies": [
      "Dog Food",
      "Dog Toys",
      "Dog Beds",
      "Leashes & Collars",
      "Dog Clothing",
      "Dog Grooming",
      "Dog Training",
      "Dog Health Care",
    ],
    "Cat Supplies": [
      "Cat Food",
      "Cat Toys",
      "Cat Beds",
      "Litter & Boxes",
      "Cat Trees",
      "Cat Grooming",
      "Cat Carriers",
      "Cat Health Care",
    ],
    "Bird Supplies": [
      "Bird Food",
      "Bird Cages",
      "Bird Toys",
      "Bird Perches",
      "Bird Houses",
      "Bird Health Care",
      "Bird Accessories",
    ],
    "Fish & Aquarium": [
      "Fish Food",
      "Aquarium Tanks",
      "Aquarium Filters",
      "Aquarium Decorations",
      "Water Treatment",
      "Aquarium Lighting",
      "Fish Health Care",
    ],
    "Small Animal Supplies": [
      "Small Animal Food",
      "Cages & Habitats",
      "Small Animal Toys",
      "Bedding",
      "Water Bottles",
      "Exercise Equipment",
    ],
    "Pet Food & Treats": [
      "Dry Food",
      "Wet Food",
      "Treats & Snacks",
      "Supplements",
      "Special Diet Food",
      "Organic Food",
    ],
    "Pet Care & Health": [
      "Flea & Tick Control",
      "Vitamins & Supplements",
      "First Aid",
      "Dental Care",
      "Skin & Coat Care",
      "Health Monitoring",
    ],
    "Pet Accessories": [
      "Pet Carriers",
      "Pet Strollers",
      "Pet Gates",
      "Travel Accessories",
      "Pet ID Tags",
      "Cleanup Supplies",
    ],
    "Pet Training": [
      "Training Treats",
      "Training Tools",
      "Clickers",
      "Training Pads",
      "Behavioral Aids",
    ],
  },
  Automotive: {
    "Car Parts & Components": [
      "Engine Parts",
      "Brake Components",
      "Suspension Parts",
      "Transmission Parts",
      "Exhaust Systems",
      "Filters",
      "Belts & Hoses",
    ],
    "Car Electronics": [
      "Car Audio",
      "GPS & Navigation",
      "Dash Cams",
      "Car Alarms",
      "Bluetooth Adapters",
      "Backup Cameras",
    ],
    "Car Care & Maintenance": [
      "Motor Oil",
      "Car Wash Products",
      "Wax & Polish",
      "Car Cleaners",
      "Maintenance Tools",
      "Fluids",
    ],
    "Tires & Wheels": [
      "Tires",
      "Wheels",
      "Tire Accessories",
      "Wheel Covers",
      "Tire Pressure Monitors",
    ],
    "Interior Accessories": [
      "Seat Covers",
      "Floor Mats",
      "Steering Wheel Covers",
      "Air Fresheners",
      "Interior Organizers",
      "Sunshades",
    ],
    "Exterior Accessories": [
      "Car Covers",
      "Roof Racks",
      "Running Boards",
      "Mud Flaps",
      "License Plate Frames",
      "Decals",
    ],
    "Tools & Equipment": [
      "Jump Starters",
      "Tire Gauges",
      "Mechanics Tools",
      "Car Jacks",
      "Emergency Kits",
      "Diagnostic Tools",
    ],
    "Motorcycle Parts": [
      "Motorcycle Parts",
      "Motorcycle Accessories",
      "Motorcycle Gear",
      "Helmets",
      "Protective Clothing",
    ],
  },
  "Health & Wellness": {
    "Vitamins & Supplements": [
      "Multivitamins",
      "Vitamin D",
      "Vitamin C",
      "B Vitamins",
      "Omega-3",
      "Probiotics",
      "Protein Supplements",
      "Herbal Supplements",
    ],
    "Medical Equipment": [
      "Blood Pressure Monitors",
      "Thermometers",
      "Glucose Meters",
      "Pulse Oximeters",
      "Stethoscopes",
      "Medical Scales",
    ],
    "First Aid & Safety": [
      "First Aid Kits",
      "Bandages",
      "Antiseptics",
      "Pain Relief",
      "Emergency Supplies",
      "Safety Equipment",
    ],
    "Fitness & Exercise Equipment": [
      "Home Gym Equipment",
      "Cardio Machines",
      "Weights & Dumbbells",
      "Resistance Bands",
      "Yoga Mats",
      "Exercise Bikes",
    ],
    "Health Monitoring": [
      "Fitness Trackers",
      "Smart Scales",
      "Heart Rate Monitors",
      "Sleep Trackers",
      "Health Apps",
    ],
    "Mobility & Daily Living": [
      "Mobility Aids",
      "Grab Bars",
      "Bath Safety",
      "Seat Cushions",
      "Daily Living Aids",
    ],
    "Alternative Medicine": [
      "Essential Oils",
      "Aromatherapy",
      "Massage Tools",
      "Acupuncture",
      "Natural Remedies",
    ],
    "Personal Care": [
      "Oral Care",
      "Incontinence Care",
      "Hearing Aids",
      "Vision Care",
      "Skin Care",
    ],
  },
};

// Category-specific keyword to subcategory mapping
export const categoryKeywordToSubcategoryMap: Record<
  string,
  Record<string, string>
> = {
  "Clothing & Fashion": {
    dress: "Dresses",
    shirt: "Tops & Shirts",
    pants: "Bottoms",
    jacket: "Outerwear",
    underwear: "Underwear & Sleepwear",
    swimwear: "Swimwear",
    sportswear: "Activewear",
    suit: "Suits & Formal",
  },
  Footwear: {
    sneakers: "Sneakers & Athletic",
    "casual shoes": "Casual Shoes",
    "formal shoes": "Formal Shoes",
    boots: "Boots",
    sandals: "Sandals & Flip-Flops",
    slippers: "Slippers",
  },
  Accessories: {
    jewelry: "Jewelry",
    watches: "Watches",
    belts: "Belts",
    hats: "Hats & Caps",
    scarves: "Scarves & Wraps",
    sunglasses: "Sunglasses & Eyewear",
  },
  "Mother & Child": {
    "baby clothing": "Baby Clothing",
    "kids clothing": "Kids Clothing",
    toys: "Toys & Games",
    "baby care": "Baby Care",
    maternity: "Maternity",
    strollers: "Strollers & Car Seats",
    feeding: "Feeding & Nursing",
    safety: "Safety & Security",
  },
  "Home & Furniture": {
    furniture: "Living Room Furniture",
    bedding: "Textiles & Soft Furnishing",
    decor: "Home Decor",
    kitchen: "Kitchen & Dining",
    bathroom: "Bathroom",
    lighting: "Lighting",
    storage: "Storage & Organization",
  },
  "Beauty & Personal Care": {
    skincare: "Skincare",
    makeup: "Makeup",
    haircare: "Haircare",
    fragrances: "Fragrances",
    "personal care": "Personal Hygiene",
    "nail care": "Nail Care",
    "body care": "Body Care",
  },
  "Bags & Luggage": {
    handbags: "Handbags",
    backpacks: "Backpacks",
    luggage: "Travel Luggage",
    briefcases: "Briefcases & Business Bags",
    "sport bags": "Sports & Gym Bags",
    wallets: "Wallets & Small Accessories",
  },
  Electronics: {
    smartphones: "Smartphones & Accessories",
    computers: "Computers & Laptops",
    tvs: "TVs & Home Entertainment",
    audio: "Audio Equipment",
    gaming: "Gaming",
    "smart home": "Smart Home & IoT",
    cameras: "Cameras & Photography",
    wearables: "Wearable Tech",
    appliances: "Home Appliances",
  },
  "Sports & Outdoor": {
    fitness: "Fitness & Exercise",
    sports: "Sports",
    "water sports": "Water Sports",
    outdoor: "Outdoor & Camping",
    "winter sports": "Winter Sports",
    cycling: "Cycling",
    running: "Running & Athletics",
  },
  "Books, Stationery & Hobby": {
    books: "Books & Literature",
    "office supplies": "Office & School Supplies",
    "art supplies": "Art & Craft Supplies",
    writing: "Writing Instruments",
    paper: "Paper Products",
    educational: "Educational Materials",
    hobbies: "Hobbies & Collections",
  },
  "Tools & Hardware": {
    "hand tools": "Hand Tools",
    "power tools": "Power Tools",
    hardware: "Hardware & Fasteners",
    electrical: "Electrical Supplies",
    plumbing: "Plumbing Supplies",
    safety: "Safety Equipment",
    measuring: "Measuring Tools",
  },
  "Pet Supplies": {
    dog: "Dog Supplies",
    cat: "Cat Supplies",
    bird: "Bird Supplies",
    fish: "Fish & Aquarium",
    "small animals": "Small Animal Supplies",
    "pet food": "Pet Food & Treats",
    "pet care": "Pet Care & Health",
  },
  Automotive: {
    "car parts": "Car Parts & Components",
    "car electronics": "Car Electronics",
    "car care": "Car Care & Maintenance",
    tires: "Tires & Wheels",
    interior: "Interior Accessories",
    exterior: "Exterior Accessories",
  },
  "Health & Wellness": {
    vitamins: "Vitamins & Supplements",
    medical: "Medical Equipment",
    "first aid": "First Aid & Safety",
    fitness: "Fitness & Exercise Equipment",
    "health monitoring": "Health Monitoring",
    mobility: "Mobility & Daily Living",
  },
};

// Fashion-specific fields
export const clothingGenders = ["Men", "Women", "Kids", "Unisex"];

export const clothingSizes = [
  "XXS",
  "XS",
  "S",
  "M",
  "L",
  "XL",
  "XXL",
  "3XL",
  "4XL",
];

export const clothingFits = ["Slim", "Regular", "Loose", "Oversized"];

export const clothingTypes = [
  "Cotton",
  "Polyester",
  "Wool",
  "Silk",
  "Denim",
  "Leather",
  "Linen",
  "Nylon",
];

// Keep existing data that wasn't in the Dart file
export const jewelryTypes = [
  "Necklace",
  "Earring",
  "Piercing",
  "Ring",
  "Bracelet",
  "Anklet",
  "NoseRing",
  "Set",
];

export const jewelryMaterials = [
  "Iron",
  "Steel",
  "Gold",
  "Silver",
  "Diamond",
  "Copper",
];

export const pantSizesByCategory = {
  Women: [
    "XXS / 32",
    "XS / 34",
    "S / 36",
    "M / 38",
    "L / 40",
    "XL / 42",
    "XXL / 44",
    "XXXL / 46",
    "4XL / 48",
    "5XL / 50",
    "24",
    "6XL / 52",
    "25",
    "7XL / 54",
    "26",
    "8XL / 56",
    "27",
    "9XL / 58",
    "28",
    "10XL / 60",
    "29",
    "30",
    "31",
    "32",
    "33",
  ],
  Men: [
    "L",
    "L/XL",
    "XL",
    "XXL",
    "2XL",
    "3XL",
    "4XL",
    "5XL",
    "6XL",
    "7XL",
    "29",
    "30",
    "31",
    "32",
    "33",
    "34",
    "36",
    "38",
    "40",
    "42",
    "44",
    "46",
    "48",
    "50",
    "52",
    "54",
    "56",
    "58",
    "XXXL",
    "8XL",
    "XS",
    "S",
    "S/M",
    "M",
  ],
};

export const footwearSizesByCategory = {
  Women: ["35", "36", "37", "38", "39", "40", "41", "42", "43"],
  Men: ["39", "40", "41", "42", "43", "44", "45", "46", "47", "48"],
  Kids: ["28", "29", "30", "31", "32", "33", "34", "35", "36"],
};

export const colorOptions = [
  { name: "Blue", hex: "#0000FF" },
  { name: "Orange", hex: "#FFA500" },
  { name: "Yellow", hex: "#FFFF00" },
  { name: "Black", hex: "#000000" },
  { name: "Brown", hex: "#A52A2A" },
  { name: "Dark Blue", hex: "#00008B" },
  { name: "Gray", hex: "#808080" },
  { name: "Pink", hex: "#FFC0CB" },
  { name: "Red", hex: "#FF0000" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Green", hex: "#008000" },
  { name: "Purple", hex: "#800080" },
  { name: "Teal", hex: "#008080" },
  { name: "Lime", hex: "#00FF00" },
  { name: "Cyan", hex: "#00FFFF" },
  { name: "Magenta", hex: "#FF00FF" },
  { name: "Indigo", hex: "#4B0082" },
  { name: "Amber", hex: "#FFBF00" },
  { name: "Deep Orange", hex: "#FF5722" },
  { name: "Light Blue", hex: "#ADD8E6" },
  { name: "Deep Purple", hex: "#673AB7" },
  { name: "Light Green", hex: "#90EE90" },
  { name: "Dark Gray", hex: "#A9A9A9" },
  { name: "Beige", hex: "#F5F5DC" },
  { name: "Turquoise", hex: "#40E0D0" },
  { name: "Violet", hex: "#EE82EE" },
  { name: "Olive", hex: "#808000" },
  { name: "Maroon", hex: "#800000" },
  { name: "Navy", hex: "#000080" },
  { name: "Silver", hex: "#C0C0C0" },
];
