// lib/constants/region.dart

// Main regions
export const mainRegions: string[] = [
  "Gazimağusa",
  "Girne",
  "Güzelyurt",
  "İskele",
  "Lefke",
  "Lefkoşa",
];

// Regional hierarchy mapping
export const regionHierarchy: Record<string, string[]> = {
  Lefkoşa: [
    "Akıncılar",
    "Alayköy",
    "Arabahmet",
    "Balıkesir",
    "Beyköy",
    "Cihangir",
    "Cyprus Internation University (CIU)",
    "Çağlayan",
    "Çukurova",
    "Değirmenlik",
    "Demirhan",
    "Dereboyu",
    "Derince",
    "Dikmen",
    "Dilekkaya",
    "Düzova",
    "Ercan",
    "Erdemli",
    "Gayretköy",
    "Gaziler",
    "Gaziköy",
    "Göçmenköy",
    "Gökhan",
    "Gönyeli",
    "Gürpınar",
    "Hamitköy",
    "Haspolat",
    "İkidere",
    "Kalavaç",
    "Kanlıköy",
    "Kargı",
    "Kırıkkale",
    "Kırklar",
    "Kızılbaş",
    "Köşklüçiftlik",
    "Kumsal",
    "Küçük Kaymaklı",
    "Marmara",
    "Meriç",
    "Metehan (Kermia)",
    "Minareliköy",
    "Near East University (NEU)",
    "Ortaköy",
    "Suriçi",
    "Taşkınköy",
    "Terminal",
    "Türkeli",
    "Yeniceköy",
    "Yenikent",
    "Yenişehir",
    "Yılmazköy",
    "Yiğitler",
  ],

  Gazimağusa: [
    "Akdoğan",
    "Akova",
    "Alaniçi",
    "Arıdamı",
    "Aslanköy",
    "Atlılar",
    "Baykal",
    "Beyarmudu",
    "Canbulat",
    "Çamlıca",
    "Çanakkale",
    "Çayönü",
    "Çınarlı",
    "DAÜ",
    "Derinya",
    "Dörtyol",
    "Dumlupınar",
    "Düzce",
    "Ergenekon",
    "Geçitkale",
    "Glapsides",
    "Gönendere",
    "Görneç",
    "Gülseren",
    "Güvercinlik",
    "İncirli",
    "İnönü",
    "Kaliland",
    "Karakol",
    "Korkuteli",
    "Köprülü",
    "Kurudere",
    "Mallıdağ",
    "Maraş",
    "Mormenekşe",
    "Muratağa",
    "Mutluyaka",
    "Nergisli",
    "Palm Beach",
    "Paşaköy",
    "Pile",
    "Pınarlı",
    "Pirhan",
    "Sakarya",
    "Saklıkent Area",
    "Sandallar",
    "Serdarlı",
    "Sosyal Konutlar (DAÜ Yanı)",
    "Sosyal Konutlar Apartmanlar",
    "Suriçi",
    "Sütlüce",
    "Tatlısu",
    "Tekant",
    "Tirmen",
    "Turunçlu",
    "Tuzla",
    "Türkmenköy",
    "Ulukışla",
    "Vadili",
    "Yamaçköy",
    "Yeniboğaziçi",
    "Yıldırım",
  ],

  Girne: [
    "Ağırdağ",
    "Akçiçek",
    "Akdeniz",
    "Alemdağ",
    "Alsancak",
    "Arapköy",
    "Aşağı Dikmen",
    "Aşağı Taşkent",
    "Bahçeli",
    "Bellapais",
    "Beşparmak",
    "Beylerbeyi",
    "Boğazköy",
    "Çamlıbel",
    "Çatalköy",
    "Dağyolu",
    "Doğanköy",
    "Edremit",
    "Esentepe",
    "Girne American University",
    "Geçitköy",
    "Girne Merkez",
    "Aşağı Girne",
    "Göçeri",
    "Güngör",
    "Hisarköy",
    "Ilgaz",
    "İncesu",
    "Karaağaç",
    "Karakum",
    "Karaman",
    "Karmi",
    "Karaoğlanoğlu",
    "Karpaşa",
    "Karşıyaka",
    "Kayalar",
    "Kılıçaslan",
    "Koruçam",
    "Kozan",
    "Kömürcü",
    "Lapta",
    "Malatya",
    "Ozanköy",
    "Özhan",
    "Pınarbaşı",
    "Sadrazamköy",
    "Şirinevler",
    "Tepebaşı",
    "Yeşiltepe",
    "Yukarı Dikmen",
    "Yukarı Taşkent",
    "Zeytinlik",
  ],

  Güzelyurt: [
    "Akçay",
    "Aşağı Bostancı",
    "Aydınköy",
    "Gayretköy",
    "Güneşköy",
    "Güzelyurt",
    "Kalkanlı",
    "Mevlevi",
    "Serhatköy",
    "Şahinler",
    "Yayla",
    "Yukarı Bostancı",
    "Yuvacık",
    "Zümrütköy",
  ],

  İskele: [
    "Adaçay",
    "Ağıllar",
    "Altınova",
    "Ardahan",
    "Avtepe",
    "Aygün",
    "Bafra",
    "Balalan",
    "Boğaz",
    "Boğaziçi",
    "Boğaztepe",
    "Boltaşlı",
    "Büyükkonuk",
    "Çayırova",
    "Derince",
    "Dipkarpaz",
    "Ergazi",
    "Esenköy",
    "Gelincik",
    "İskele Bahçeler",
    "İskele Merkez",
    "Kaleburnu",
    "Kalecik",
    "Kantara",
    "Kaplıca",
    "Kilitkaya",
    "Kumyalı",
    "Kurtuluş",
    "Kuruova",
    "Kuzucuk",
    "Long Beach",
    "Mehmetçik",
    "Mersinlik",
    "Ötüken",
    "Pamuklu",
    "Sazlıköy",
    "Sınırüstü",
    "Sipahi",
    "Taşlıca",
    "Topçuköy",
    "Turnalar",
    "Tuzluca",
    "Yarköy",
    "Yedikonuk",
    "Yeni Erenköy",
    "Yeşilköy",
    "Zeybekköy",
    "Ziyamet",
  ],

  Lefke: [
    "Aplıç",
    "Bademliköy",
    "Bağlıköy",
    "Cengizköy",
    "Çamlıköy",
    "Denizli",
    "Doğancı",
    "Erenköy",
    "Gaziveren",
    "Gemikonağı",
    "Günebakan",
    "Kurutepe",
    "Lefke",
    "Madenliköy",
    "Ömerli",
    "Şirinköy",
    "Taşköy",
    "Taşpınar",
    "Yedidalga",
    "Yeşilırmak",
    "Yeşilyurt",
  ],
};

// Flattened list of all regions (main + sub) sorted alphabetically
export const allRegionsList: string[] = [
  "Adaçay",
  "Ağıllar",
  "Ağırdağ",
  "Akçay",
  "Akçiçek",
  "Akdeniz",
  "Akdoğan",
  "Akıncılar",
  "Akova",
  "Alaniçi",
  "Alayköy",
  "Alemdağ",
  "Alsancak",
  "Altınova",
  "Aplıç",
  "Arabahmet",
  "Arapköy",
  "Ardahan",
  "Arıdamı",
  "Aslanköy",
  "Aşağı Bostancı",
  "Aşağı Dikmen",
  "Aşağı Girne",
  "Aşağı Taşkent",
  "Atlılar",
  "Avtepe",
  "Aydınköy",
  "Aygün",
  "Bademliköy",
  "Bafra",
  "Bağlıköy",
  "Bahçeli",
  "Balalan",
  "Balıkesir",
  "Baykal",
  "Bellapais",
  "Beşparmak",
  "Beyarmudu",
  "Beyköy",
  "Beylerbeyi",
  "Boğaz",
  "Boğaziçi",
  "Boğazköy",
  "Boğaztepe",
  "Boltaşlı",
  "Büyükkonuk",
  "Canbulat",
  "Cengizköy",
  "Cihangir",
  "Cyprus Internation University (CIU)",
  "Çağlayan",
  "Çamlıbel",
  "Çamlıca",
  "Çamlıköy",
  "Çanakkale",
  "Çatalköy",
  "Çayırova",
  "Çayönü",
  "Çınarlı",
  "Çukurova",
  "Dağyolu",
  "DAÜ",
  "Değirmenlik",
  "Demirhan",
  "Denizli",
  "Dereboyu",
  "Derince",
  "Derinya",
  "Dikmen",
  "Dilekkaya",
  "Dipkarpaz",
  "Doğancı",
  "Doğanköy",
  "Dörtyol",
  "Dumlupınar",
  "Düzce",
  "Düzova",
  "Edremit",
  "Ercan",
  "Erdemli",
  "Erenköy",
  "Ergazi",
  "Ergenekon",
  "Esenköy",
  "Esentepe",
  "Gayretköy",
  "Gaziköy",
  "Gaziler",
  "Gazimağusa",
  "Gaziveren",
  "Geçitkale",
  "Geçitköy",
  "Gelincik",
  "Gemikonağı",
  "Girne",
  "Girne American University",
  "Girne Merkez",
  "Glapsides",
  "Göçeri",
  "Göçmenköy",
  "Gökhan",
  "Gönendere",
  "Gönyeli",
  "Görneç",
  "Gülseren",
  "Günebakan",
  "Güneşköy",
  "Güngör",
  "Gürpınar",
  "Güvercinlik",
  "Güzelyurt",
  "Hamitköy",
  "Haspolat",
  "Hisarköy",
  "Ilgaz",
  "İkidere",
  "İncesu",
  "İncirli",
  "İnönü",
  "İskele",
  "İskele Bahçeler",
  "İskele Merkez",
  "Kalavaç",
  "Kaleburnu",
  "Kalecik",
  "Kaliland",
  "Kalkanlı",
  "Kanlıköy",
  "Kantara",
  "Kaplıca",
  "Karaağaç",
  "Karakol",
  "Karakum",
  "Karaman",
  "Karaoğlanoğlu",
  "Kargı",
  "Karmi",
  "Karpaşa",
  "Karşıyaka",
  "Kayalar",
  "Kılıçaslan",
  "Kırıkkale",
  "Kırklar",
  "Kızılbaş",
  "Kilitkaya",
  "Korkuteli",
  "Koruçam",
  "Kozan",
  "Kömürcü",
  "Köprülü",
  "Köşklüçiftlik",
  "Kumsal",
  "Kumyalı",
  "Kurtuluş",
  "Kurudere",
  "Kuruova",
  "Kurutepe",
  "Kuzucuk",
  "Küçük Kaymaklı",
  "Lapta",
  "Lefke",
  "Lefkoşa",
  "Long Beach",
  "Madenliköy",
  "Malatya",
  "Mallıdağ",
  "Maraş",
  "Marmara",
  "Mehmetçik",
  "Meriç",
  "Mersinlik",
  "Metehan (Kermia)",
  "Mevlevi",
  "Minareliköy",
  "Mormenekşe",
  "Muratağa",
  "Mutluyaka",
  "Near East University (NEU)",
  "Nergisli",
  "Ortaköy",
  "Ozanköy",
  "Ömerli",
  "Ötüken",
  "Özhan",
  "Palm Beach",
  "Pamuklu",
  "Paşaköy",
  "Pınarbaşı",
  "Pınarlı",
  "Pile",
  "Pirhan",
  "Sadrazamköy",
  "Sakarya",
  "Saklıkent Area",
  "Sandallar",
  "Sazlıköy",
  "Serdarlı",
  "Serhatköy",
  "Sınırüstü",
  "Sipahi",
  "Sosyal Konutlar (DAÜ Yanı)",
  "Sosyal Konutlar Apartmanlar",
  "Suriçi",
  "Sütlüce",
  "Şahinler",
  "Şirinevler",
  "Şirinköy",
  "Taşkınköy",
  "Taşköy",
  "Taşlıca",
  "Taşpınar",
  "Tatlısu",
  "Tekant",
  "Tepebaşı",
  "Terminal",
  "Tirmen",
  "Topçuköy",
  "Turnalar",
  "Turunçlu",
  "Tuzla",
  "Tuzluca",
  "Türkeli",
  "Türkmenköy",
  "Ulukışla",
  "Vadili",
  "Yamaçköy",
  "Yarköy",
  "Yayla",
  "Yedidalga",
  "Yedikonuk",
  "Yeni Erenköy",
  "Yeniboğaziçi",
  "Yeniceköy",
  "Yenikent",
  "Yenişehir",
  "Yeşilırmak",
  "Yeşilköy",
  "Yeşiltepe",
  "Yeşilyurt",
  "Yıldırım",
  "Yılmazköy",
  "Yiğitler",
  "Yukarı Bostancı",
  "Yukarı Dikmen",
  "Yukarı Taşkent",
  "Yuvacık",
  "Zeybekköy",
  "Zeytinlik",
  "Ziyamet",
  "Zümrütköy",
];

// Helper function to get subregions for a main region.
export const getSubregions = (mainRegion: string): string[] => {
  return regionHierarchy[mainRegion] ?? [];
};

// Helper function to get the main region for a subregion
export const getMainRegion = (subregion: string): string | null => {
  for (const mainRegion of mainRegions) {
    if (regionHierarchy[mainRegion]?.includes(subregion) == true) {
      return mainRegion;
    }
  }
  return null;
};

export default allRegionsList;
